### PR TITLE
Fix missing Relay import in examples

### PR DESCRIPTION
**Pull request by kassens**
Test Plan:
For every example `npm install` and `npm start` then open it in a browser and
see it render.

### CODE REVIEW

**Comment by kassens** [comment]
@facebook-github-bot import

**Comment by akashnimare** [comment]
Dude I removed those relay import line because it is unused var. Lint was showing that var relay is not used so I removed it.

**Comment by yungsters** [comment]
cc @zpao @spicyj 

I assume this is an implicit dependency due to JSX? Is this something we could fix in `eslint-plugin-react`?

**Comment by spicyj** [comment]
Yeah, you're supposed to import React. I guess that could be a nice lint rule, though in some cases React will be a global so you wouldn't want to warn.

**Comment by yungsters** [comment]
> though in some cases React will be a global so you wouldn't want to warn.

But in that case, we should use the existing ESLint mechanisms for declaring `React` as a global, right?

----

Regardless, @kassens :+1:

**Comment by zpao** [comment]
Yep. You'll want to enable https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md

**Comment by spicyj** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md too.

**Comment by yungsters** [comment]
Ahh, nice.

@kassens Can you incorporate @zpao's suggestion so that this pull request does not re-introduce the lint errors?

**Pull request closed without merging**
