### PR TITLE
Make sure Travis CI doesn't `npm install` twice

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by kassens** [comment]
Nice.

We could also move `cd $TEST_DIR && npm install` into the install script.

**Comment by steveluscher** [comment]
Oh, don't worry. #1114.

**Comment by steveluscher** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1594574400870343/int_phab) to review.

**Pull request closed without merging**
