### PR TITLE
Typo: Missing period on Relay.RootContainer

### PR DESCRIPTION
**Pull request by washt**
RelayRootContainer should be Relay.RootContainer

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by josephsavona** [comment]
This should really be `<Relay.Renderer ... />` ([docs](https://facebook.github.io/relay/docs/api-reference-relay-renderer.html#content), we haven't updated all the docs to reference it yet. Would you care to update this usage?

**Comment by washt** [comment]
Sure!

**Comment by steveluscher** [comment]
Nice! Can I impose on your generosity even further, and ask that you replace the Root Container guide with a Relay Renderer guide in a follow up PR, now that you're on a roll?

@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1834783863424838/int_phab) to review.

**Comment by washt** [comment]
Of course, no problem :+1:

**Pull request closed without merging**
