### PR TITLE
unbreak LiveState unsub when references.size === 0

### LINKED ISSUE #4830: @live LiveState unsubscribe cleanup function never gets called
```ts
/**
 * @RelayResolver Query.liveSubUnsubTest: Int
 * @live
 */
export function liveSubUnsubTest(): LiveState<number> {
  return {
    read() {
      console.log("liveSubUnsubTest", "read")
      return Date.now()
    },
    subscribe(didChange) {
      console.log("liveSubUnsubTest", "subscribe")
      const id = setInterval(() => {
        console.log("liveSubUnsubTest", "tick")
        didChange()
      }, 1234)
      return function unsubscribe() {
        console.log("liveSubUnsubTest", "unsubscribe")
        clearInterval(id)
      }
    },
  }
}
```

```tsx
function LiveSubUnsubTestDemo() {
  const data = useClientQuery<LiveState__LiveSubUnsubTestDemo__Query>(
    graphql`
      query LiveState__LiveSubUnsubTestDemo__Query {
        liveSubUnsubTest
      }
    `,
    {},
  )

  if (!data.liveSubUnsubTest) {
    return <Text className="text-white">MIA</Text>
  }

  return (
    <>
      <Text className="text-white">
        {new Date(data.liveSubUnsubTest).toLocaleString()}
      </Text>
    </>
  )
}
```

after unmounting `LiveSubUnsubTestDemo`, I'm still getting the subscription ticks forever

```
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
 LOG  liveSubUnsubTest tick
```

`console.log("liveSubUnsubTest", "unsubscribe")` is never called

### PR DESCRIPTION
**Pull request by subtleGradient**
fixes #4830 by ensuring that there is only a single path for evicting stuff, ensuring that `maybeResolverSubscription` gets called correctly

### CODE REVIEW

**Comment by captbaritone** [comment]
Thank you for this. Great catch. Would you mind adding a test case here: https://github.com/facebook/relay/blob/f4c37a333575341b78979106084068cb6b27e1cf/packages/relay-runtime/store/__tests__/resolvers/ResolverGC-test.js so that we don't regress this again?

**Comment by subtleGradient** [comment]
@captbaritone added the test.
I couldn't figure out how to get the `__generated__` stuff to build, 
so I reused an existing fragment name, not sure if that matters or not

manually verified that the test fails before the fix and passes after the fix

**Comment by subtleGradient** [comment]
bummed this didn't make it into 18.2
What still needs to happen before this can land? @captbaritone

**Comment by captbaritone** [comment]
Sorry for the poor communication. We are in a code freeze currently so not landing any high risk changes that are not necessary, so I wanted to wait to land this one. I'm out next week, but can try to get this landed when I return.

**Pull request closed without merging**
