### PR TITLE
Add a better error message regarding Watchman failures

### LINKED ISSUE #2951: Errors with Watchman not being reported
**Bug description**

Attempting to running `relay-compiler` on watch mode with Watchman, I was presented the following message:

```
Zaguinis-MBP:relay-test zaguini$ yarn relay --watch
yarn run v1.15.2
$ relay-compiler --src ./src --schema ./schema.graphql --extensions js jsx --watch
Watchman is required to watch for changes. Running with watch mode disabled.
```

Which was weird since I had Watchman installed. I tried running Watchman and that's what I've got:

```
Zaguinis-MBP:relay-test zaguini$ watchman
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/Cellar/watchman/4.9.0_2/libexec/bin/watchman
  Reason: image not found
Abort trap: 6
```

Meaning that there was an error within Watchman. Reinstalling it solved the issue for me.
But that's not enough. I mean, I went through it to investigate, but this error message is not transparent enough. Very silent.

**Expected behavior**

A better error message, something like:

```If you are sure Watchman is installed, try running `watchman` to check for errors```

**Actual behavior**

A not very descriptive error messaging:

```Watchman is required to watch for changes. Running with watch mode disabled.```

### PR DESCRIPTION
**Pull request by zaguiini**
Fixes #2951

### CODE REVIEW

**Comment by josephsavona** [comment]
Awesome, thanks!

**Comment by zaguiini** [comment]
I see that one check failed, @josephsavona. Is there something I can do?

**Comment by josephsavona** [comment]
I can fix before landing, all good!

**Comment by damassi** [comment]
Any chance this can be merged? Just ran into this issue as well.

**Pull request closed without merging**
