### PR TITLE
Request for feedback: Add eslint-plugin-graphql to example

### PR DESCRIPTION
**Pull request by stubailo**
I don't know if you would want to merge this or not, but I'm working on an ESLint plugin for GraphQL validation.

screenshot 2016-04-25 23 26 25

The benefit over the babel relay plugin is that you can see and fix the errors right in your editor, and there's even a nice underline!

Here's the repo for the linter plugin: https://github.com/apollostack/eslint-plugin-graphql

It's not perfect yet, but I'm curious what you think of this direction, and what improvements you would want to see in such a tool!

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by wincent** [comment]
This is sweet.

CC @yuzhi, who's been thinking about validation lately (eg. https://github.com/graphql/graphql-js/pull/355).

**Comment by stubailo** [comment]
Oh that's a great improvement, will make the error messages much more helpful!

**Comment by dguillamot** [comment]
@stubailo  This looks awesome. Are you thinking of adding a warning for fragment data that is requested but not used? Similar to 'no-unused-vars' ? http://eslint.org/docs/rules/no-unused-vars

**Comment by stubailo** [comment]
@dguillamot right now that's disabled, because in Relay/Lokka you often compose fragments, so you have strings like `fragment on Post {...}` which by themselves would trigger that error.

Do you have an app where that would be useful?

Just filed an issue, let's discuss there: https://github.com/apollostack/eslint-plugin-graphql/issues/10

**Comment by wincent** [comment]
Closing this as the examples have moved into [a separate `relay-examples` repo](https://github.com/relayjs/relay-examples) now (not public as of the time I write this, but will be hopefully within a day or two; we just need to get the person with the right privileges to flip a switch) so this PR won't apply here.

I don't know if you're still working on that plugin @stubailo, but I'd be welcome to adding it to the example over in the new repo.

**Comment by stubailo** [comment]
Yeah the plugin pretty much just works! So I'll resubmit to the new repo.

**Comment by wincent** [comment]
Cool. I'll ping you when it's public.

**Comment by wincent** [comment]
@stubailo and it's public... https://github.com/relayjs/relay-examples

**Pull request closed without merging**
