### PR TITLE
Update connections documentation

### PR DESCRIPTION
**Pull request by kendepelchin**

### CODE REVIEW

**Comment by rbalicki2** [comment]
Thanks for making this change! Can you go ahead and update the unversioned file, as well? Otherwise, looks great!

**Comment by davidmccabe** [comment]
Thanks!!

**Comment by davidmccabe** [comment]
@rbalicki2  There have been a few PRs that don't update the versioned file, so I'll just let them all land and then do another diff where I sync the two. (Very easy to do in batch, just a `cp` command)

**Comment by kendepelchin** [comment]
> Thanks for making this change! Can you go ahead and update the unversioned file, as well? Otherwise, looks great!
> 
> 
> 
> 

Sorry didn't see this as fast as I wanted. I can always update it if needed

**Pull request closed without merging**
