### PR TITLE
Fix issue where queries with multiple fields on the same Connection get sorted out of order.

### PR DESCRIPTION
**Pull request by HurricaneJames**
This is related to #478, where having multiple fields that query for different ranges on a Connection come back in random order causing the RelayQueryWriter to get confused and fail to build all the edges.

### CODE REVIEW

**Comment by wincent** [comment]
Thanks for the PR, @HurricaneJames.

We originally added the type-first sorting — somewhat reluctantly — to satisfy an internal requirement (integration with another cache that relied on type-first behavior; D2022689 for any FBers that might be reading along). I'm going to check around and see whether this is still a requirement (I expect it is) and if we can fork this particular detail so that the open source world doesn't have to deal with this.

**Comment by HurricaneJames** [comment]
If it is a requirement, then it might work to modify the sort algorithm to only sort type first and not alphanumeric.

I switched to a different task for the next couple hours, but something like

```
function sortTypeFirst(a: string, b: string): number {
  if (a === b) { return 0; }
  if (a === TYPE) { return -1; }
  if (b === TYPE) { return 1;  }
  return 0;
}
```

should still sort type first, but leave the sequencing alone otherwise.

**Comment by HurricaneJames** [comment]
Alright, so I was too curious to try and see if it would work. It does seem to fix the problem I found, but it also causes tests to fail. Fortunately, it looks like just tests for `sortTypeFirst` which expected the previous behavior of sorting for type first and name second. I do not see anywhere else that uses the sortTypeFirst algorithm in the code, so perhaps this change is acceptable.

**Comment by HurricaneJames** [comment]
@winent did we ever find out if this could be merged or if we needed to use the alternate sort algorithm?

**Comment by wincent** [comment]
I don't think we want to drop the sorting entirely, as we want printed queries to preserve the ordering of the original underlying query (other than the noted constraint that types have to come first) for consistency, determinism and debuggability.

It seems that once #479 is resolved, your issue hopefully will be too. @josephsavona is actively working on addressing that, although it is a multi-step process with no quick fix.

**Comment by HurricaneJames** [comment]
Git sometimes sucks. I tried to change the PR to the new sort method and merge that change, but it got all messed up. It would take longer to figure out than just to refork. So I'm just doing that.

New PR: #523

**Pull request closed without merging**
