### PR TITLE
Remove Haste configuration from .flowconfig

### PR DESCRIPTION
**Pull request by AlicanC**
Removed Haste stuff from .flowconfig and refactored the project accordingly so when Flow types are shipped on NPM (#2690) users won't have to configure Haste on their projects.

### CODE REVIEW

**Comment by zth** [comment]
This is great!

**Comment by AlicanC** [comment]
I thought I did it, but didn't realize the builds were broken. (I guess it was cached on my local.)

Trying to fix that right now.

**Comment by AlicanC** [comment]
@alunyov I was working on this, but your latest commit 9dc19e3 broke the whole thing for me. (`relay-test-utils-internal` can not be found.)

**Comment by alunyov** [comment]
@AlicanC sorry for that. I'm working on the fix now

**Comment by jstejada** [comment]
cc @kassens

**Comment by kassens** [comment]
The problem here is that internally, we use the source code as is without going through npm. Internally, we have the `warning` module etc, but no `fbjs/lib/warning`, so we need to require `warning` directly.

I should think of a workaround, some of the modules we could probably just get rid of or inline..

**Pull request closed without merging**
