### PR TITLE
Allow clientMutationId to be null

### PR DESCRIPTION
**Pull request by freiksenet**
As per #258

### CODE REVIEW

**Comment by wincent** [comment]
I've imported this into our internal Phabricator instance so we can get some other eyes on it. Thanks for the PR, @freiksenet.

**Comment by josephsavona** [comment]
Relay currently assumes that `clientMutationId` is non-null; we should add the requisite invariant checks before updating the spec.

**Comment by freiksenet** [comment]
Does it assume that in the schema or in result? Current spec enforces resulting `clientMutationId` to be non-null if it was passed in query, so relay will always get it and not getting it is a valid error.

**Comment by josephsavona** [comment]
I see, I was probably being overly cautious. :+1:

**Pull request closed without merging**
