### PR TITLE
adds Lattice as a Relay user :)

### PR DESCRIPTION
**Pull request by jaylattice**
Hello! This PR adds [Lattice](https://lattice.com/) as a Relay user. We're using Relay in production to serve over 1300 companies with our awesome HR software.

### CODE REVIEW

**Comment by jstejada** [comment]
@jaylattice I'm going to add this to `siteConfig.js` instead, since USERS.md is no longer being used to power the users page.

We need an image to add it to the users page, is this the correct image to use for Lattice? https://www.lingoapp.com/a/453BB96F-E40C-4BDF-8CDB-8F1FFA0EC387/430Fj-TkrxrR6w0FJE8-UYCacGIPDcM2W3o_CgddbC4/?v=0

**Comment by alloy** [comment]
(At Artsy we use Lattice 👌 We’ve come full circle 😁)

**Comment by jaylattice** [comment]
@jstejada That's the right one. Thanks!

**Comment by jaylattice** [comment]
Hey @jstejada it looks like there's a typo in the `` link for the logo: `src` should point to `"/img/logos/lattice_logo_full_color.png"` but curretly points to `"/img/logos/latice_logo_full_color.png"`.

image

**Pull request closed without merging**
