### PR TITLE
Create flat bundles using rollup

### PR DESCRIPTION
**Pull request by robrichard**
Updated the gulpfile to use Rollup to generate commonjs and umd bundles as discussed here: https://github.com/facebook/relay/issues/1590. I followed the pattern used by the master branch of React for requiring the dev or prod enabled versions.

I'm being very explicit with regard to what modules are external vs included in the bundles. Let me know there is a different way you would like to handle it. 

Also what is the best way I can test that these bundles are built correctly and working as expected?

### CODE REVIEW

**Comment by robrichard** [comment]
Hey @leebyron @kassens - are you still considering using Rollup to build the new relay packages as discussed in https://github.com/facebook/relay/issues/1590? If so it would be good to get it in before the final 1.0.0 release, otherwise it will be a breaking change. It would removes access to internal modules, e.g. `require('react-relay/lib/toGraphQL')`

**Comment by kassens** [comment]
Interesting, hadn't thought of that. This would probably be a good thing though as we should expose all necessary things publicly.

**Comment by alloy** [comment]
@kassens @jstejada Reading the history of this PR, it does seem like there was interest on FB’s side to merge such an external contribution. Does that still apply?

**Comment by robrichard** [comment]
I did try to rebase that PR a few months ago and ran into some issues with the dynamic requires of the relay dev tools.

Also it would be much more beneficial if the relay source was updated to use ES modules as was done in the React source code. By using `rollup-plugin-commonjs` here, each module will still be wrapped in a closure.

**Comment by alloy** [comment]
@robrichard Is that something that can be done iteratively?

**Comment by robrichard** [comment]
@alloy hard for me to say as I don't know how it would mesh with FB's custom module system.

**Comment by alloy** [comment]
I meant more, can this PR continue as-is and discuss ES6 modules as a next step or is blocked by that by now?

Also, out of curiosity, does React not use the Haste module system?

**Comment by robrichard** [comment]
Yes this change would not be blocked by that.

React was converted to ES modules in these two PRs:
https://github.com/facebook/react/pull/11303
https://github.com/facebook/react/pull/11389

**Comment by robrichard** [comment]
Going to close this as there are a few issues with this approach:
1. The rollup config is complicated by the way files are imported without relative file paths.
2. The source files use CommonJS, meaning that rollup still requires wrapping them in a closure function, meaning the final bundle is not truly flat.

**Pull request closed without merging**
