### PR TITLE
Rename babel plugin

### PR DESCRIPTION
**Pull request by devknoll**
Renames the babel plugin internally, fixing #256. A follow up PR will change the package.json to use the new plugin name.

### CODE REVIEW

**Comment by BerndWessels** [comment]
@devknoll @steveluscher @josephsavona Will this replace the `babel-relay-plugin` on NPM ?
If so it should still be in sync with the version number of `react-relay` to avoid confusion ?!
But it looks like there is a `1.0.0` published to NPM - but `react-relay` is only `0.6.1`.
Can you please fix this or am I mistaken here?

**Comment by devknoll** [comment]
@BerndWessels Yes, the intention would be to publish a `babel-plugin-relay@0.6.3` at the same time as deprecated `babel-relay-plugin@0.6.3`.

**Comment by BerndWessels** [comment]
@devknoll OK, but why is there a `babel-plugin-relay` with version `1.0.0` already published to NPM? That seems wrong and might lead to confusion?

**Comment by BerndWessels** [comment]
@devknoll Oh, I see - just for holding on to the name on NPM - so you will delete the `1.0.0` later I guess.

**Comment by josephsavona** [comment]
@devknoll import this!

**Comment by devknoll** [comment]
@facebook-github-bot import

**Comment by yungsters** [comment]
So besides rebasing, what else do we need to do to get this in?

**Comment by josephsavona** [comment]
A quick update here: we understand that this can be helpful in OSS. At the same time, we use this plugin heavily internally, and this PR requires quite a bit of work to successively land and reconfigure things in a few environments. It's a lot of work and doesn't seem to be super high-value relative to other feature requests and core improvements. 

The easiest thing might be to temporarily provide two packages, where `babel-relay-plugin` just re-exports `babel-plugin-relay` (or vice-versa). That way we can make the change, and then as a follow-up go back and update our internal configuration w/o breakage.

Anyone interested in working on this?

**Comment by josephsavona** [comment]
I'm going to close this - see my previous comment for more context. We're happy to do the rename, but it has to be gradual in order to not break things.

**Pull request closed without merging**
