### PR TITLE
Start moving readRelayQueryData tests over to use writePayload

### PR DESCRIPTION
**Pull request by wincent**
Part of the effort to enable us to change the internal storage format without having to manually update hundreds of test cases. More to come after this commit.

### CODE REVIEW

**Comment by steveluscher** [comment]
Sorry we left this so long, and now it's a rebase-tastrophe. :(

**Comment by wincent** [comment]
Yeah, I wanted to import it but then parenting. Probably easiest to just reroll it, which I'll do.

/literally sent from phone while laboring over a hot stove

**Comment by josephsavona** [comment]
@wincent we didn't end up changing the store format (yet) - should we just close this and continue with it later if necessary?

**Comment by wincent** [comment]
@josephsavona: @yungsters was asking me about this yesterday. I was going to reroll it, but it didn't seem like the highest impact thing I could to so I just let it sit. Closing is the right call for now!

**Pull request closed without merging**
