### PR TITLE
Curry printRequireModuleDependency with extension; add relative ./ path

### PR DESCRIPTION
**Pull request by babangsund**
Suggested fix for https://github.com/facebook/relay/issues/2713

### CODE REVIEW

**Comment by babangsund** [comment]
Not being able to see what tests and linters are failing on internally is kind of annoying. 😅

**Comment by mrtnzlml** [comment]
@babangsund This creates the following path:

```
"operation": require('./LocationsPaginatedRefetchRefetchQuery.graphqljs'),
```

There is a missing dot for the extension, it should be this:


```diff
- "operation": require('./LocationsPaginatedRefetchRefetchQuery.graphqljs'),
+ "operation": require('./LocationsPaginatedRefetchRefetchQuery.graphql.js'),
```

**Comment by sibelius** [comment]
@mrtnzlml can you send a pr fixing this?

**Comment by mrtnzlml** [comment]
@sibelius Cannot promise. Is there already some existing test for this file or should I create a new test?

**Comment by sibelius** [comment]
you can add another test

**Pull request closed without merging**
