### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by lucasweng**
A wrong variable `query` is being used in the code example. The `usePreloadedQuery` should take the `AppQuery`.

Edit: Also fix the same typos in the `useQueryLoader` code example.

### CODE REVIEW

**Comment by poteto** [comment]
Thanks @lucasweng! Could you update the [versioned docs](https://github.com/facebook/relay/blob/master/website-v2/versioned_docs/version-v11.0.0/api-reference/hooks/use-preloaded-query.md) as well?

**Comment by lucasweng** [comment]
Sure! Out of curiosity, will the [current doc](https://github.com/facebook/relay/blob/master/website-v2/docs/current/api-reference/hooks/use-preloaded-query.md) automatically get updated once the versioned doc is updated? Or they need to be manually updated at the same time?

**Comment by poteto** [comment]
"current" is essentially the main branch for the docs. Whenever we cut a docs release, whatever is on current gets versioned for that particular release. Our docs site also serves docs from the latest versioned doc (11), not current. This workflow makes sense if we're making changes to APIs that warrant doc updates that need versioning, but simple typo fixes and whatnot don't really fit in that well.

cc @jstejada @rbalicki2 who are looking at ways of improving this in the future

**Comment by lucasweng** [comment]
Thanks for explaining it @poteto!

**Comment by poteto** [comment]
Also sorry, you'll need to rebase this before I can land

**Comment by rbalicki2** [comment]
FYI — I made a feature request to docusaurus to have a feature that makes it easy to copy changes from the unversioned docs to versioned docs. Feel free to upvote! https://docusaurus-2.netlify.app/feedback/p/feature-request-sync-staged-changes-from-unversioned-docs-to-latest-versioned-do

**Pull request closed without merging**
