### PR TITLE
Solving issues for relay 0.9 and it examples

### PR DESCRIPTION
**Pull request by CoericK**
Adding this will allow run the examples on /examples directory.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by CoericK** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by CoericK** [comment]
@facebook-github-bot import

**Comment by josephsavona** [comment]
@CoericK thanks for the PR. We'll take a look and import this as soon as we can.

**Comment by CoericK** [comment]
Np @josephsavona, hope I can get involve more on the comunity.

**Comment by steveluscher** [comment]
I'm pretty confident that the root issue is #1177 – namely that npm `preinstall` no longer works as we expect it does. We used to `preinstall` all of Relay and the Babel plugin before even starting to pull in the example apps' dependencies. Npm >=v3 changed how `preinstall` behaves. Our fix for this is to forego this entire step, and install the _release_ versions of Relay and the Babel plugin for use in the example apps (#1183). This should work for most people, most of the time.

**Pull request closed without merging**
