### PR TITLE
Guide Update

### PR DESCRIPTION
**Pull request by juangl**
Just erasing markdown inside the code, as it is not parsed.

If you don't like my way just please change that, because could be confused with `template strings`.

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by wincent** [comment]
Thanks for the PR, @juangl.

Using Markdown style formatting in comments is a convention that we follow widely (not just in samples in the documentation, but in the source code as well, in this and in other repos too) so this is not a change that we would want to make unless we were doing it consistently everywhere, which would require further discussion.

So I am going to close this for now. If you feel strongly about changing the convention please open an issue and we'll label it with the "discussion" label and we can talk about it further. I do worry that this would tend to be somewhat of a bikeshed issue, and I also think that in a case like this the value of sticking to a well-established convention outweighs the cost of conversion, and the cost of possible confusion that people might feel seeing backticks inside of comments (note: if you are concerned that people might see them as template literals, are you also worried that they might perceive single and double-quoted strings as string literals?).

Thanks once again for the submission though.

**Comment by juangl** [comment]
@wincent Thanks for response. I will be more specific. It gets confusing particulary  when backticks  are inside a template literal. I won't open a issue because I also think that is not too relevant, but I make you know.

```
Relay.QL`
  # This fragment only applies to objects of type `User`.
  fragment on User {
    # Set the `size` argument to a GraphQL variable named `$size` so that we can
    # later change its value via the slider.
    profilePhoto(size: $size) {
      # Get the appropriate URI for the given size, for example on a CDN.
      uri,
    },
  }
`
```

**Comment by wincent** [comment]
I see, thanks for clarifying. So it's not confusing; it's actually syntactically invalid. We should definitely fix those ones, but leave the others as they were before. Want to submit an update?

**Comment by juangl** [comment]
@wikichen Sure! It's done. Hope your review.

**Comment by wincent** [comment]
Thanks!

**Comment by wincent** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-5** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3793191) to review internal test results.

**Pull request closed without merging**
