### PR TITLE
Prevents RelayNetworkDebug from breaking fetch

### PR DESCRIPTION
**Pull request by finneganh**
RelayNetworkDebug overwrites the global 'fetch' function with one that
does not return a Promise. Additionally, it calls that 'fetch' without a
correct 'this'.

Fixes the overwrite to correctly invoke a global 'fetch' and also
preserve its return value.

I think this should be covered under an existing corporate CLA with Twitter.

### CODE REVIEW

**Comment by yuzhi** [comment]
@finneganh Thank you for your pull request. After using this a bit internally, we found that this way of blatantly overwriting the inject network layer is somewhat fragile.  Instead of making it wrap around an `injectedNetworkLayer`, I am actually in the process of rewriting RelayNetworkDebug to be more of a subscriber to `RelayNetworkLayer`.

**Comment by finneganh** [comment]
Sounds good! Thanks for the update.

**Comment by wincent** [comment]
I think we can close this out now that @yuzhi's new take on `RelayNetworkDebug` has landed in 85158ce9f88cf3c93015106e1d1df64b64b49d85. Let me know if I'm mistaken @finneganh, and thanks for contributing!

**Comment by finneganh** [comment]
Cool, looking forward to that getting in a release.

**Comment by wincent** [comment]
Yep, probably worth cutting a release soon.

**Comment by kassens** [comment]
I just published 0.8.1 with the fix.

**Pull request closed without merging**
