### PR TITLE
Support printing ObjectValue arguments

### PR DESCRIPTION
**Pull request by jquense**
In service of #1708 and complete support of relayIR. I added a test but Jest refused to run on my system, watchman was just staling and eating all my CPU cycles.

### CODE REVIEW

**Comment by KyleAMathews** [comment]
How's this look Relay folks?

**Comment by wincent** [comment]
Looks reasonable to me.

**Comment by jquense** [comment]
can confirm it's working in our version in Gatsby as well :)

**Comment by jquense** [comment]
Updated. more complete support of ListValue and nested cases.

**Comment by leebyron** [comment]
Very nice! I'll help get this landed

**Comment by jquense** [comment]
🙇 thanks!

**Pull request closed without merging**
