### PR TITLE
Contextualize RelayRenderer

### PR DESCRIPTION
**Pull request by denvned**
This PR is another step toward making all Relay state contextual (#558). Originally this was submitted as a part of #683, but @josephsavona [suggested](https://github.com/facebook/relay/pull/683#issuecomment-166386149) to split it to smaller PRs.

### CODE REVIEW

**Comment by denvned** [comment]
Updated with the master.

Tests started failing recently. Looks like Jest can't find `ReactDOMServer`.
Cc @cpojer

**Comment by cpojer** [comment]
See https://github.com/facebook/relay/blob/master/scripts/jest/preprocessor.js#L46 – the correct path or node module needs to be added there :)

**Comment by raineroviir** [comment]
I added this to the file above `'ReactDOMServer': 'react/lib/ReactDOMServer'` and it fixed the test

**Comment by cpojer** [comment]
Can you send a separate PR for that? :)

**Comment by raineroviir** [comment]
sure

**Comment by denvned** [comment]
I already did https://github.com/facebook/relay/pull/854/files

**Comment by raineroviir** [comment]
okay cool :+1:

**Comment by josephsavona** [comment]
This is a great PR - yay tests!

@facebook-github-bot import

**Comment by josephsavona** [comment]
@facebook-github-bot import

**Pull request closed without merging**
