### PR TITLE
Use fragment variables in RefetchContainer docs

### PR DESCRIPTION
**Pull request by josephsavona**
RefetchContainer and PaginationContainer were designed for use with fragment-local variables. This updates the documentation to reference and use this feature.

### CODE REVIEW

**Comment by josephsavona** [comment]
Relates to #1770

**Comment by lukecwilliams** [comment]
@josephsavona  I believe the second instance of `graphql` should also be `graphql.experimental`.

I'm also getting these errors when trying to compile this code - working on debugging, is this meaningful to you?


    -- Relay Transform Error -- TreatList --

    File:  dist/react-components/TreatList.js
    Error: TypeError: Cannot read property 'toString' of undefined
    at RelayQLType.getName (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLAST.js:468:86)
    at RelayQLType.mayImplement (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLAST.js:618:17)
    at shouldGenerateIdFragment (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:567:27)
    at RelayQLPrinter.printFragment (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:171:18)
    at RelayQLPrinter.print (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:86:32)
    at RelayQLTransformer.transform (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLTransformer.js:65:56)
    at compileRelayQLTag (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/compileRelayQLTag.js:24:24)
    at createRelayQLTemplate (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:288:42)
    at createFragmentForOperation (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:274:10)
    at createOperationConcreteNode (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:60:52)
TypeError: Cannot read property 'toString' of undefined
    at RelayQLType.getName (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLAST.js:468:86)
    at RelayQLType.mayImplement (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLAST.js:618:17)
    at shouldGenerateIdFragment (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:567:27)
    at RelayQLPrinter.printFragment (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:171:18)
    at RelayQLPrinter.print (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLPrinter.js:86:32)
    at RelayQLTransformer.transform (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/RelayQLTransformer.js:65:56)
    at compileRelayQLTag (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/compileRelayQLTag.js:24:24)
    at createRelayQLTemplate (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:288:42)
    at createFragmentForOperation (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:274:10)
    at createOperationConcreteNode (/Users/Luke/Projects/ClientPOC/node_modules/babel-plugin-relay/lib/createClassicNode.js:60:52)

**Comment by lukecwilliams** [comment]
Going further, it looks like Relay Compiler just isn't generating files in __generated__ for the graphqlexperimental calls.

Relay compiler gives:

```
Created:
 - AddTreatEntryMutation.graphql.js
 - DeleteTreatEntryMutation.graphql.js
 - AddWorkoutEntryMutation.graphql.js
 - UpdateWaistSizeMutation.graphql.js
 - DeleteWorkoutEntryMutation.graphql.js
 - TreatListQuery.graphql.js
 - TreatList_userData.graphql.js
```

But only the first 5 files are in the directory.  Only the Mutation files are created, not the Query ones.

**Comment by josephsavona** [comment]
Ooops you're right

**Comment by lukecwilliams** [comment]
FYI - I couldn't get rid of the shouldGenerateIdFragment errors in compat mode.  However everything is converted on our end, and switching to Modern fully does not generate this Babel error.

**Pull request closed without merging**
