### PR TITLE
[VSCode Extension] Support for multiple relay configs

### PR DESCRIPTION
**Pull request by tbezman**
## Goal

Support repositories with multiple Relay configs when using the VSCode Extension. 

### Changes

We had to subtly change the architecture of the extension to be more contextual around a given project. We still support the happy path of no configuration required if you have a relay config in your root.

- **Breaking Change**: `relay.pathToConfig` and `relay.rootDirectory` have been deprecated in favor of `relay.projects`, an array of `{ pathToConfig: string, rootDirectory: string }`. 
- Instead of a global `RelayExtensionContext`, we now have a `RelayExtensionContext` with `projects` inside, and a `RelayProjectExtensionContext`. The latter is used for project specific functions in the extension code.
- Logging looks a bit better with a prefixed `[Project Name] ` in the output so you know which project is causing that output. This is done by passing a contextual logger function around.
- The extension's commands execute across all of the projects. Warning / Error messages should only show once per command as not to create a jarring UX.

### Testing
- I tested this out on the https://github.com/relayjs/relay-examples repo (thanks @captbaritone for the suggestion).
- I have a PR over there with configuration for this next release ready to go once this lands (https://github.com/relayjs/relay-examples/pull/235)

### Demo

Here's a demo in the relay-examples repo, one extension, multiple projects, multiple LSPs running based on the configuration in https://github.com/relayjs/relay-examples/pull/235

https://user-images.githubusercontent.com/6754223/175756716-800673e4-9ba9-40ca-a3c3-af686d007cd2.mp4

### CODE REVIEW

**Comment by cvle** [comment]
Anyway to move this PR forward?

**Comment by tbezman** [comment]
@cvle I had no idea this never landed. Working w/ the team to get this in now

**Review by kmiddleton14 — COMMENTED** [review]
Apologies for the wait @tbezman! Our team had a couple followup questions that I pasted back into this PR

**Comment by badrange** [comment]
Now that relay 15 is out I went and checked what was the status of this work. Are you planning to move this forward @tbezman?

**Comment by ernieturner** [comment]
@badrange I've taken over ownership of this and am actively working on it. I moved changes to a [separate PR](https://github.com/facebook/relay/pull/4238) just to have better ownership on it. Hopefully we'll get this other PR merged soon. @tbezman we can probably close down this PR if you want to.

**Comment by badrange** [comment]
Thanks for the update @ernieturner. Following the new PR, looking forward to getting the extension working properly in our project.

**Comment by tbezman** [comment]
Closing since @ernieturner took over.

**Pull request closed without merging**
