### PR TITLE
Link to persisted queries in tutorial

### PR DESCRIPTION
**Pull request by robinpokorny**
Use correct name and add link to Persisted queries

### CODE REVIEW

**Comment by captbaritone** [comment]
Oops. Looks like this also includes #4355.

**Comment by robinpokorny** [comment]
So, there are more problems with tutorial later on. Should I create one bigger PR or several small ones?

**Comment by captbaritone** [comment]
Multiple small PRs is generally better.

**Comment by captbaritone** [comment]
Looks like GitHub is reporting merge conflicts. Would you mind rebasing?

**Comment by captbaritone** [comment]
ping @robinpokorny waiting on rebase

**Comment by robinpokorny** [comment]
Fixed :)

**Pull request closed without merging**
