### PR TITLE
Make GraphQLStoreChangeEmitter contextual

### PR DESCRIPTION
**Pull request by devknoll**
Builds on #562. Part of #558

### CODE REVIEW

**Comment by josephsavona** [comment]
@facebook-github-bot import

**Comment by josephsavona** [comment]
See comments on https://github.com/devknoll/relay/commit/3f654dc3028fdc9654020b894af376763900ee36. Also, would you mind rebasing now that the first 3 commits have landed?

**Comment by devknoll** [comment]
@josephsavona Looks like all of those changes were made, just in a later commit (99ead02)

*edit*: This is suuuuper confusing, haha. Let me rebase and see if 99ead02 can be moved to this PR.

**Comment by devknoll** [comment]
@josephsavona Done. Rebased on master and rearranged the commits for the `GraphQLStoreQueryResolver` changes to come first.

I'll go back and get the rest of the PRs updated now.

**Comment by josephsavona** [comment]
awesome, i'll land these together

**Pull request closed without merging**
