### PR TITLE
Community Resources: add link to Relay examples repository

### PR DESCRIPTION
**Pull request by mrtnzlml**
Hello guys! 👋 

We had internal Relay workshop some time ago and we decided to record some parts and share it with the community along with short documentation as well as with working code. I believe this could serve as a good source of information even for other people working with Relay.

Thanks for considering it.

### CODE REVIEW

**Comment by sibelius** [comment]
this is awesome

my only feedback is about the color of videos

image

it is the same color of apollo docs

**Comment by mrtnzlml** [comment]
@sibelius That's just a coincidence. Definitely not an intention. The guy who created these videos used our own company color (unfortunately the old one - should be this https://orbit.kiwi/visual-style/color/).

Also, I checked their docs and seems like it's quite different? https://www.apollographql.com/docs/ Either way, they were using our color... :D

**Comment by mrtnzlml** [comment]
Hi, is here anything I can do to make this PR better (mergeable)? :)

**Comment by jstejada** [comment]
Thanks for adding this, apologies we didn't get to it sooner!

**Pull request closed without merging**
