### PR TITLE
Add support for client schemas

### PR DESCRIPTION
**Pull request by edvinerikson**
Makes it possible to have a client schema. Not sure if it should be changed to only allow one schema file or if this is good enough.

Forked @kassens changes and made some fixes to get it to work.

### CODE REVIEW

**Comment by sibelius** [comment]
@kassens @jstejada can we get this for 1.5.0?

**Comment by jstejada** [comment]
addressing #1656

**Comment by alloy** [comment]
@jstejada It looks like you tried to import this patch, but I guess it failed? Can you see what’s up?

**Comment by jstejada** [comment]
@edvinerikson thanks!

**Pull request closed without merging**
