### PR TITLE
Add configuration option to keep both ID and query text in artifacts

### PR DESCRIPTION
**Pull request by xuorig**
This pull request is not complete, but I'd love to get your thoughts before pushing it further.

We are currently in the process of adopting PQs. However, we want to do so progressively.  An approach we're interested in is keeping both the original text and the `id` on the client, meaning we could dynamically switch between IDs and full query documents at runtime. In this PR I've added a config option that enables this behaviour.

It's a bit challenging to test given that the current compiler tests don't exercise the code path leading to the generation of an ID, so I may need to use another approach if going for this solution.

### CODE REVIEW

**Comment by xuorig** [comment]
Just pushed another approach to this problem that feels less brittle. Moving the logic of deciding which params to keep to the persister instead. This feels a bit better, the current logic was executed during serialization of the artifacts which required a more generic approach. This really feels more like a persister-level decision. Thoughts?

**Comment by soneymathew** [comment]
This feature landed in relay as part of this PR
https://github.com/facebook/relay/pull/3917
Can this approach work for you?

**Comment by xuorig** [comment]
@rbalicki2 apologies for the direct ping, but we would still appreciate a feature like this in Relay rather than using a custom fork. Anything we can do to push this PR forward (or this one https://github.com/facebook/relay/pull/3917)?

**Comment by captbaritone** [comment]
Thanks for the PR @xuorig. I've decided to start with @tomgasson's PR, but as he pointed out, you are both on the same page. Would you mind doing a review of https://github.com/facebook/relay/pull/3917 to see if there's anything that you noticed while implementing this PR that we might have missed over there?

**Comment by captbaritone** [comment]
I'm going to close this for now, but I'll be happy to reopen if https://github.com/facebook/relay/pull/3917 doesn't end up working out.

**Pull request closed without merging**
