### PR TITLE
disable text transform on buttons

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
uppercase text is unreadable, especially when the text used to be camelcase.

**Comment by kassens** [comment]
Sorry to have this linger a bit, but I was waiting for Docusaurus to go open source. I don't think we should start forking styles here and instead see if that's something that could be changed upstream at https://github.com/facebook/docusaurus

**Comment by graingert** [comment]
Can we at least merge this for the fixed custom CSS 404?

**Comment by kassens** [comment]
Good call, I'll update the this PR before landing than!

**Pull request closed without merging**
