### PR TITLE
docs(NetworkLayer): add custom open-source implementations

### PR DESCRIPTION
**Pull request by nodkz**
[react-relay-network-modern](https://github.com/nodkz/react-relay-network-modern) was rewritten from scratch for Relay Modern. It has almost identical options and plugins which have previous [Network Layer for Relay Classic](https://github.com/nodkz/react-relay-network-layer). So in most cases, it is a drop-in replacement for users which migrates from Classic to Modern. It has a clear code, tests, and covered by flowtype.

### CODE REVIEW

**Comment by kassens** [comment]
Sorry this got trashed a bit, the good news is that once the new system is setup, we should have a lot better round trip time from PR to website (couple minutes instead of whenever someone goes through the old website deploy script that never worked well)

**Comment by alloy** [comment]
@nodkz Care to update your PR for the new website? That link seems really helpful!

**Comment by nodkz** [comment]
Updated new PR https://github.com/facebook/relay/pull/2303

@alloy I'm very glad that somebody takes care about PRs. Are you now on the relay team?

**Comment by alloy** [comment]
I am not. I only had a chat with the team about how to gain some community traction and so I’m trying to do my part.

**Comment by nodkz** [comment]
Cool. Thanks a lot!

**Comment by alloy** [comment]
You too for your contributions!

**Pull request closed without merging**
