### PR TITLE
Optionally output eager es modules

### PR DESCRIPTION
**Pull request by TrySound**
In this PR I added `eagerESModules` option to `relay-runtime` and `babel-plugin-relay`. I have two problem which can be solved with this change

1. Rollup handles only es modules. To handle commonjs there is a plugin
which converts it into esm. Though it always skips module if
import/export statements are found. As a result I get runtime error:
"require is not defined".

To workaround this I wrote custom plugin. Though it would be cool to
have proper solution out of the box.

```js
{
  name: 'relay-generated',
  transform(code) {
    // convert __generated__ requires into imports
    // remove after relay-compiler will be able to emit esm
    if (code.includes('__generated__')) {
      let i = -1;
      const paths = [];
      const processed = code.replace(
        /require\((.+__generated__.+)\)/g,
        (req, pathString) => {
          i += 1;
          paths.push(pathString);
          return `__generated__${i}`;
        },
      );
      const imports = paths.map(
        (p, i) => `import __generated__${i} from ${p};\n`,
      );
      return {
        code: imports.join('') + processed,
      };
    }
  },
},
```

2. Another problem is flow bug (https://github.com/facebook/flow/issues/7444) which treats all not existent types as any.
This leads to many type unsafe places.

```js
import type {NotExistentType} from './__generated__/MyQuery.graphql';

type Props = {|
  my: NotExistentType
|}
```

### CODE REVIEW

**Comment by TrySound** [comment]
Hi @josephsavona. What do you think about this change?

**Comment by TrySound** [comment]
Hi @kassens Could you take look?

**Comment by johndous** [comment]
This will be very useful for people who use `rollup` to bundle their app.

**Comment by frenzzy** [comment]
PR resolves the following issue: #2445

P.S.: I linked the related issue to help people like me find a solution and of course would be great to get this feature accepted.

**Comment by TrySound** [comment]
Friendly ping @kassens @josephsavona

**Comment by johndous** [comment]
Any update on this?

**Comment by TrySound** [comment]
@kassens Do you mind to review this PR? Any changes required to move it forward?

**Comment by sgwilym** [comment]
This would be a really great addition.

**Comment by frenzzy** [comment]
I just published this feature under [`@frenzzy/babel-plugin-relay`](https://www.npmjs.com/package/@frenzzy/babel-plugin-relay).
I use the feature to run my app in browsers with es6 support without bundling to speed up dev process and I hope it may help someone else too.

**Comment by TrySound** [comment]
Hi @jstejada. Any news on this? Do you want me to assist with something?

**Comment by TrySound** [comment]
Friendly ping @jstejada

**Comment by TrySound** [comment]
Friendly ping @jstejada @kassens @alunyov. Do you need me to rebase this PR or you have something internally?

**Comment by johndous** [comment]
Hi @frenzzy! Could you please add the latest version `8.0.0` to  @frenzzy/babel-plugin-relay as this MR still remains open and we can't bundle with rollup at all... 

@jstejada @kassens @alunyov could you please merge this MR?  It's open from the summer!!

**Comment by frenzzy** [comment]
I would like to release v8, but need to resolve conflicts first, it is quite complex now after so radical changes. @TrySound can you please update your PR (rebase on master)?

**Comment by TrySound** [comment]
im out of computer til 5 jan, sorry

**Comment by frenzzy** [comment]
Just released [@frenzzy/babel-plugin-relay](https://www.npmjs.com/package/@frenzzy/babel-plugin-relay) `v8.0.0`, hope I rebased correctly (at least tests are passing). You can see the diff here: https://github.com/frenzzy/relay/commit/4d485bc179750cd1688931a196d612ddf3e211da
@TrySound thank you and enjoy your holiday :)

**Comment by TrySound** [comment]
@jstejada @kassens @alunyov @josephsavona  I updated esm output considering recent thunks removal. Tests are much smaller now too.

**Comment by TrySound** [comment]
Friendly ping @jstejada @kassens @josephsavona

**Comment by TrySound** [comment]
Yay!

**Pull request closed without merging**
