### PR TITLE
Upgrade jest to 13.2.x

### PR DESCRIPTION
**Pull request by kassens**

### CODE REVIEW

**Comment by kassens** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/107352216369946/int_phab) to review.

**Comment by cpojer** [comment]
It's actually 13.2. :P

**Comment by kassens** [comment]
Fixed

**Pull request closed without merging**
