### PR TITLE
Also test node v6 on travis

### PR DESCRIPTION
**Pull request by chentsulin**

### CODE REVIEW

**Comment by wincent** [comment]
Thanks for this, @chentsulin. Looks like we might have some work to do to make things pass before we can merge this. Want to take a look at those failures?

**Comment by chentsulin** [comment]
ok, i will take a look and try to figure out what happened.

**Comment by wincent** [comment]
@chentsulin: check out @kassens diff links above. That *might* fix it, and is *at least* related.

**Comment by kassens** [comment]
Yes, the `jest` update was required to make most of the tests pass, but there still seems to be some legit errors.

**Comment by kassens** [comment]
Thanks for sending this out, I took the liberty to include this small change with #1126 which fixes the broken unit tests.

**Pull request closed without merging**
