### PR TITLE
Add Hudl to the list of users

### PR DESCRIPTION
**Pull request by mihai**
We've been using Relay at [Hudl](https://www.hudl.com/) for over a year now.

### CODE REVIEW

**Comment by wincent** [comment]
Thankyou @mihai!

**Comment by wincent** [comment]
@facebook-github-bot shipit

**Comment by mihai** [comment]
Hey @wincent, it seems the CI build failed and this PR was never merged by the bot --  is there anything I can do to fix that?

**Comment by wincent** [comment]
@mihai: Let me see if I can force it to ship.

**Comment by wincent** [comment]
@facebook-github-bot shipit

**Pull request closed without merging**
