### PR TITLE
Using Relay without React

### PR DESCRIPTION
**Pull request by andimarek**
This PR has to the goal to make Relay usable without React.

__Overview:__
The core functions of Relay don't depend really on React, but currently it's only really useable with `RelayContainer`, which is a higher order React component.

The idea behind this PR is to introduce two new classes: `GenericRelayRootContainer` and `GenericRelayContainer`. Both are very similar to `RelayRootContainer/RelayRenderer` and `RelayContainer`. The main difference is that they don't wrap any React Component and don't deal with any rendering. They just maintain the data specified by fragments. 
Instead of rendering a Component they call a registered callback function to inform about new/changed data.
This way it is possible to use co-located data declaration with any rendering technology.

To make it more clear I added a modified star-wars example to use Angular instead React: [examples/star-wars-angular](https://github.com/andimarek/relay/tree/generic-relay-container/examples/star-wars-angular)

This is already working but it's not perfect. I'm sharing this here to get some feedback, if this is even possible to get merged and what to improve/change.
 
__Implementation Details:__
Like I said I added to new classes: [GenericRelayRootContainer](https://github.com/andimarek/relay/blob/generic-relay-container/src/container/GenericRelayRootContainer.js) and [GenericRelayContainer](https://github.com/andimarek/relay/blob/generic-relay-container/src/container/GenericRelayContainer.js).

The `GenericRelayRootContainer` combines some aspects of `RelayRootContainer` and `RelayRenderer`: It basically just calls `getRelayQueries` for the first data fetching.

`GenericRelayContainer` is a reduced version of `RelayContainer`: It's not a React Component, but a simple class.The important parts for the data declaration are the same as in `RelayContainer`: There is still a `RelayContainerSpec` and Routes are also the same. But for example because there is no React Context anymore, the route has to provided along with all the other props.

I added a few new types, but reused all of the existing types where possible/made sense.

There are also two new test files [GenericRelayContainer-test](https://github.com/andimarek/relay/blob/generic-relay-container/src/container/__tests__/GenericRelayContainer-test.js) and [GenericRelayRootContainer-test](https://github.com/andimarek/relay/blob/generic-relay-container/src/container/__tests__/GenericRelayRootContainer-test.js)

The tests are kept minimal because I think some aspects of `GenericRelayContainer` and `RelayContainer` should be pulled out into own modules to make it more DRY. I wanted to wait for some feedback before duplicating too much test cases.

### CODE REVIEW

**Comment by josephsavona** [comment]
Thanks for your contribution! It's exciting to see interest in using Relay with other view libraries. As noted in the [roadmap](https://github.com/facebook/relay/wiki/Roadmap#in-progress), we're actively on working on making Relay more modular - including separating Relay into a core, imperative data-fetching API and a declarative React integration layer. The core could then be used to implement integrations with other view libraries. 

The community has been actively contributing toward a prerequisite of this - #558 - to make all Relay state contextual instead of global, and this is almost finished. We (Relay core) are working on the core/react split - see #559.

We definitely would like to support the community in integrating Relay with other libraries. For this PR, it might be best to create a new package/repository - e.g. `relay-angular` - since you and the community will have more expertise about Angular best-practices. Note that `GenericRelay(Root)Container` is a good temporary solution for resolving Relay data until #558 and #559 are complete, at which point there will be a documented, public API for resolving data outside of Relay containers.

**Comment by andimarek** [comment]
Thanks for your feedback and the references to the issues. 

Especially your comment about `DataContainer`(https://github.com/facebook/relay/issues/559#issuecomment-155703059):
This is I think the same idea as the `GenericRelayContainer`.

I will comment on this specific issues, as it seems the better place.

**Comment by andimarek** [comment]
About the `relay-angular` suggestion: I just wanted to make clear, that the goal of this PR was not to make Relay work with Angular specifically. It was just the example I created with Angular, because I know Angular better than e.g. ember.

**Comment by andimarek** [comment]
I'm closing this PR, because the topic will be handled in #559.

**Pull request closed without merging**
