### PR TITLE
fix duck-typing

### PR DESCRIPTION
**Pull request by knowbody**
@cpojer 
RE: #102

### CODE REVIEW

**Comment by cpojer** [comment]
This is not entirely correct. Can you also rename the check from `getQuery` to `getFragment`?

**Comment by cpojer** [comment]
Also, I was about to send out this same PR, but I guess you beat me to it :P

**Comment by yungsters** [comment]
Community: 1
@cpojer: 0

**Comment by knowbody** [comment]
yeah, changing it, sorry :smile:

**Comment by cpojer** [comment]
I squashed your two commits into a single one because this was a simple fix. I hope you do not mind – thank you very much for your contribution and keep it up :)

See 3e0fa93c6a6be180bb10c7846acd95de25dd29fc

**Comment by knowbody** [comment]
of course I don't mind, I "stole" your PR lol :+1:

**Pull request closed without merging**
