### PR TITLE
[relay-compiler] add eagerESModules to yargs

### PR DESCRIPTION
**Pull request by TrySound**
Without this change I get the following error

```
Unknown argument: eagerESModules
```

### CODE REVIEW

**Comment by TrySound** [comment]
Hi @kassens @jstejada Is it possible to make patch release with this?

**Comment by TrySound** [comment]
@kassens Friendly ping

**Comment by TrySound** [comment]
@kassens @tyao1 @jstejada The feature listed in release does not work without this PR
image

**Comment by TrySound** [comment]
Friendly ping @kassens @tyao1 @jstejada

**Comment by TrySound** [comment]
Friendly ping @kassens @tyao1 @jstejada @josephsavona guys
I waited this feature since June.

**Comment by sibelius** [comment]
you can patch-package until another release

**Comment by TrySound** [comment]
Hi @kassens @tyao1 @jstejada @josephsavona guys, you ok with this change?

**Comment by jstejada** [comment]
hey @TrySound sorry for the delay, we'll get to this this week

**Pull request closed without merging**
