### PR TITLE
[docs] Translation of Relay Documentation to pt-BR

### PR DESCRIPTION
**Pull request by biantris**
Translation of Relay Documentation to pt-BR, Relay is a very useful tool for any developer nowadays and through translations to other languages helps the dissemination of the tool. Here in Brazil we love and use Relay a lot, one of the main players and specialists about here in Brazil is @sibelius, that's why I'm willing to translate your documentation via Crowdin https://crowdin.com/project/relay-pt-br

Translated or WIP files (work in progress):
- community-learning-resources 
- graphql-server-specification WIP 
- installation-and-setup WIP
- introduction-to-relay
- prerequisites
- quick-start-guide WIP

### CODE REVIEW

**Comment by daniloab** [comment]
awesome

**Comment by poteto** [comment]
Thank you very much for this @beatrizoliveiira! Let us know how we can support you, otherwise looking forward to seeing this hit the finish line!

**Comment by beatrizoliveiira** [comment]
@poteto I think the best way is to merge this pull request and I will be adding more translated documents incrementally!

**Review by GabrielBarcelos1 — APPROVED** [review]

**Comment by vit0rr** [comment]
Congrats

**Pull request closed without merging**
