### PR TITLE
remove extra word

### PR DESCRIPTION
**Pull request by DawoodShahat**
[https://github.com/facebook/relay/pull/3398](https://github.com/facebook/relay/pull/3398)

### CODE REVIEW

**Comment by poteto** [comment]
Sorry, you'll need to rebase this one before I can land it.

**Review by poteto — CHANGES_REQUESTED** [review]
Needs to be rebased, otherwise LGTM

**Comment by EmmanuelFm** [comment]
Why

**Comment by kassens** [comment]
Not exactly sure what happened here, but this was (also) fixed in 1aaeee29dad1cc98aeed3754cfcba72544898a41.


Thanks for the PR!

**Pull request closed without merging**
