### PR TITLE
add edge order specifications to Connections documentation

### LINKED ISSUE #2466: Add clarifications/missing specifications about order of edges to the relay cursor connections specification
Recently while working on improving `graphql-sequelize`'s implementation of connections, I discovered that, as far as I understand, someone misinterpreted the specification: their implementation returns `edges` in the opposite order when the `last` argument is used.  This also means the `startCursor` and `endCursor` are swapped, and their reverse pagination test fetches the previous page by requesting `last: 3, before: pageInfo.endCursor`.  But as far as I understand `before` should always take the `startCursor` of the current `pageInfo`.

I've submitted a PR to fix their implementation but I'd also like to help prevent this kind of misinterpretation for anyone in the future.

Adding the following clarifications to the Relay Cursor Connections Specification would precisely specify the ordering of `edges`:
* The ordering of `edges` should be the same when using `first/after` as when using `last/before`, all other arguments being equal
* To fetch the next page one should use `after: pageInfo.endCursor`, not `after: pageInfo.startCursor`
* To fetch the previous page one should use `before: pageInfo.startCursor`, not `before: pageInfo.endCursor`
* When `before: cursor` is used, the edge closest to `cursor` should come **last** in the result `edges`.
* When `after: cursor` is used, the edge closest to `cursor` should come **first** in the result `edges`.

**EDIT**: merrywhether pointed out that `startCursor` and `endCursor` are not standard right now, so I've updated my PR to refer to the edge cursors instead.

### PR DESCRIPTION
**Pull request by jedwards1211**
Closes #2466

### CODE REVIEW

**Comment by sibelius** [comment]
maybe you should link to relay connection handler as well https://github.com/facebook/relay/blob/master/packages/relay-runtime/handlers/connection/RelayConnectionHandler.js#L42

**Comment by jedwards1211** [comment]
@sibelius It doesn't seem quite right to me for a specification to refer to an *implementation* of the specification...a specification should be able to stand on its own, don't you think?

**Comment by jedwards1211** [comment]
@kassens did you author this spec or just copy it from elsewhere?
I want to get some FB eyes on this to comment or approve it.

**Comment by ngbrown** [comment]
Why are these changes not live on the website? (https://facebook.github.io/relay/graphql/connections.htm) 

It seems only the `graphql/` directory of the website isn't getting updated during publishes, because the most recent build on the `gh-pages` branch is from a version that includes these changes (https://github.com/facebook/relay/commit/be9e7dfc9b45125ba0afd0e27c06639f9ad7936e).

**Comment by jstejada** [comment]
@ngbrown should be live now

**Comment by jedwards1211** [comment]
Thank you guys!

**Comment by ngbrown** [comment]
@jstejada https://facebook.github.io/relay/graphql/connections.htm still doesn't have any mention of `startCursor` or `endCursor`.  The history for the `gh-pages` branch shows no recent activity in the /graphql directory. https://github.com/facebook/relay/tree/gh-pages/graphql

**Pull request closed without merging**
