### PR TITLE
Build: Fix build by adding missing module mappings.

### LINKED ISSUE #1482: npm run build fails on master
## Steps to reproduce
1. `git clone git@github.com:facebook/relay.git`
2. `cd relay`
3. `yarn install`

`npm run build`/`gulp` is run as part of the post-install and fails with: 

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./lib/deepFreeze.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./babel-runtime/core-js/object/is-frozen in /Users/Michael/Development/relay/lib
resolve file
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.webpack.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.web.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.json doesn't exist
resolve directory
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen doesn't exist (directory default file)
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen/package.json doesn't exist (directory description file)
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.webpack.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.web.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/is-frozen.json]
 @ ./lib/deepFreeze.js 22:40-91./lib/deepFreeze.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./babel-runtime/core-js/object/get-own-property-names in /Users/Michael/Development/relay/lib
resolve file
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.webpack.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.web.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.json doesn't exist
resolve directory
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names doesn't exist (directory default file)
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names/package.json doesn't exist (directory description file)
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.webpack.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.web.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/object/get-own-property-names.json]
 @ ./lib/deepFreeze.js 24:51-115./lib/RelayGraphQLTag.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./babel-runtime/core-js/weak-map in /Users/Michael/Development/relay/lib
resolve file
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.webpack.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.web.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.js doesn't exist
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.json doesn't exist
resolve directory
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map doesn't exist (directory default file)
  /Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map/package.json doesn't exist (directory description file)
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.webpack.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.web.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.js]
[/Users/Michael/Development/relay/lib/babel-runtime/core-js/weak-map.json]
 @ ./lib/RelayGraphQLTag.js 17:39-82
```

Before it fails it displays some warnings as well:

```
        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 6.8. To find out the caller, grep for this
        message and change it to a `console.trace()`.


        You or one of the Babel plugins you are using are using Flow declarations as bindings.
        Support for this will be removed in version 6.8. To find out the caller, grep for this
        message and change it to a `console.trace()`.
```

A regular `npm run build` fails in the same way. `npm run build` works at the `v0.10.0` tag but outputs the same warnings. 

I know in the contributing guide it says that [master is unsafe](https://github.com/facebook/relay/blob/master/CONTRIBUTING.md#master-is-unsafe) but that seems to be more geared towards API stability rather than just flat out not being able to build.

### PR DESCRIPTION
**Pull request by alloy**
Fixes #1482

### CODE REVIEW

**Comment by josephsavona** [comment]
@facebook-github-bot shipit

**Comment by josephsavona** [comment]
@alloy so good, thank you for taking the time to figure this out! 

Cc @kassens

**Comment by alloy** [comment]
My pleasure 👍

**Comment by alloy** [comment]
Don’t think any of these build failures are a result of my change. It looks like some (most/all?) are caused by incorrect dependencies? Maybe it’s an idea to lock dependencies to known working versions, e.g. a npm/yarn lockfile. I can take a stab at that in a separate PR, if you’d like?

**Comment by colllin** [comment]
This fixed the build for me, but I also needed to add this 4th mapping:

    'babel-runtime/core-js/map': 'babel-runtime/core-js/map',

**Comment by alloy** [comment]
@colllin Oh, what task was failing?

**Comment by colllin** [comment]
The postinstall build was failing.  I think it was `npm run build` but I'm not 100% since I didn't run it manually.

**Comment by alloy** [comment]
@colllin Ah I see, it’s a new requirement since this this change that got added after my PR eab5a45b8a648564037e36cdb668abf9154b9ef3. Will add it 👍

**Comment by alloy** [comment]
Done.

**Comment by kassens** [comment]
Thanks for fixing this!

**Pull request closed without merging**
