### PR TITLE
Add support for esmodules for provided variables

### PR DESCRIPTION
**Pull request by bigfootjon**
Fixes: #3966

I based my implementation on https://github.com/facebook/relay/commit/0c4108d630d67356f0b65e526201b5e7ccd78d29 and https://github.com/facebook/relay/commit/efd9d867ba7e4e984f27abe469a2e6c455bb1dc0

Not great that we're duplicating the code for this around the codebase, happy to clean things up if anyone has any ideas.

Test plan:

??? I'm not really sure how to use this for my personal project locally and the test suite doesn't have any existing tests and my knowledge of Jest is... lacking.

### CODE REVIEW

**Comment by captbaritone** [comment]
Thanks!

**Comment by mofeiZ** [comment]
Thanks for trying out provided variables + helping us making this more usable for open source! 

I think we'll also need to add type generation changes in the `relay-typegen` crate. Relay generate types for every provided variable used by a query to ensure that the provider module (1) exists and (2) exports a function of the correct type.
- The code lives in`src/write.rs` ->`generate_provided_variables_type`

The current TypeScript (+ flow) type-generation would produce types that look like this:
```
// graphql`
//  fragment Foo @argumentDefinitions(x : {type: "Float", provider: "getValue"}) {
//    my_field(arg: $x)
//  }
type ProvidedVariablesType = {
  readonly __relay_internal__pv__getValue: {
    readonly get: () => number | null;
  };
};

const providedVariablesDefinition: ProvidedVariablesType = {
  "__relay_internal__pv__getValue": require('./getValue')
};
```

**Comment by captbaritone** [comment]
@bigfootjon are you still interested in working on this? If not we can close it.

**Comment by bigfootjon** [comment]
Yeah sorry I don’t have the bandwidth to finish this :(

**Pull request closed without merging**
