### PR TITLE
Mongoose example

### PR DESCRIPTION
**Pull request by sayden**
Hi,

I think it is a good idea to have an example of Relay using a real database instead of data stored in an array. This example shows how to use Relay with a MongoDB database, mainly following the principles of the Star Wars example.

Main differences: 
* Does not use graphql-relay. While graphql-relay library empowers productivity, it hides some concepts of graphql and makes it a bit more difficult to understand. Instead, NodeInterface and NodeField are defined in the schema.
* No [name]Database.js. Instead, you can find a Models folder within data folder. There you can find Mongoose schemas and CRUD functions that returns promises.

I have also added some features:
* `npm run restart` script to rebuild schema and start server
* `npm run print-schema` script to print the schema on graphql format on a file within data folder.
* `npm run print-instrospection`. The same than above but with introspection.
* `npm run populate` A script to populate a local MongoDB database with some Mock data. This mock data are some of the most influential programmers in computer science history (including Mark Zuckerberg, of course).
* *Readme* file with an explanation of the example.

Thank you very much

Mario Castro
mariocaster@gmail.com
0034 689 11 10 10

### CODE REVIEW

**Comment by steveluscher** [comment]
This is fantastic. Can I use this for an upcoming Relay Community Roundup?

We've discussed the notion of adding more examples to the Relay repository [before](https://github.com/facebook/relay/pull/128#issuecomment-134620980) but feel like we're not the right people to maintain more than a handful of them in the long-term. We would, however, *love* if you would publish this under your own GitHub account, and would be happy to answer questions and review code.

Some of your npm commands might be useful in the starter-kit, and I'd be happy to merge in some PRs [there](https://github.com/relayjs/relay-starter-kit).

How does that sound?

**Comment by josephsavona** [comment]
This is great. I agree with @steveluscher that this is ultimately best placed in a separate repo.

A few suggestions though:
- By not using `graphql-relay-js`, there's less guarantee that the root fields and mutation will work with Relay. For example, Relay requires that all mutations accept a single argument `input` - [see the spec](http://facebook.github.io/relay/docs/graphql-mutations.html#content) - but the mutations here don't follow this pattern and won't work with `Relay.Mutation`. Also it would probably be best to include an example for each root field (`users` and `hobbies` return lists of items, which is currently unsupported, see #112 )
- file naming is inconsistent (`.js` but some `.es6`)

**Comment by sayden** [comment]
Hi,

Sure Steve, you everybody can use the example, I will feel very proud :)

Project is currently maintained in my own github account in https://github.com/sayden/relay-mongoose-example (forked from relay-starter-kit) so I can keep pushing on it. I will also make a pull-request on the starter kit to add the `restart`, `print-schema` and `print-introspection` scripts. While I will keep an eye on relay as I feel it like the new "holy-grail" in cs. :)

Joseph, I really appreciate that you point me my mistakes. While I like pretty much GraphQL and Relay technologies I still feel a bit confused with the documentation and some of the obscure things of graphql-relay library.

By the way, I develop `hobbies` and `users` mainly to check the integrity of the data through curl / postman after mutations.

I was also trying to develop a more structured file tree like in this repo I started to learn a bit more of graphql https://github.com/sayden/graphql-mongodb-example/tree/master/Models/User but I was facing cyclical dependencies problems when adding a interface.

Thank you very much again.

**Comment by spyalert01** [comment]
Wow... this is good.
thanks

**Comment by josephsavona** [comment]
Great, feel free to file issues if you encounter any more issues during development. I'm going to close this out now that you have it on your own repo. Thanks!

**Comment by spyalert01** [comment]
Hi @sayden ,
I downloaded your script. and npm run update-schema, then npm run start.
I goto browser, and I see blank page. 
How should I run and test your script and mutation?

**Comment by spyalert01** [comment]
Hi @sayden 
Here is my 
UserSchema
=========== user schema start =========
let UserSchema = new mongoose.Schema({
  id: {
    type: String,
    required: true,
    unique: true,
    index: true,
    default: mongoose.Types.ObjectId
  },
  name: String,
  surname: String,
});

UserSchema.set('toJSON', {getters: true});
let ModUser = mongoose.model('User', UserSchema);

exports.UserSchema = ModUser;

exports.getModUserById = () => {
	return new Promise((resolve, reject) => {
		ModUser.findOne().exec((err, res) => {
			if(err){
				reject(err);
			}else{
				resolve(res);
			}
			//err ? reject(err) : resolve(res);
		})
	});
};
================ user schme stop ===========


and here is my schema.js 

==== partial schema.js start -====== 
import ModUser from './modules/ModUser.js';

var appUserType = new GraphQLObjectType({
  name: 'AppUser',
  description: 'A person who uses our app',
  fields: () => ({
    id: globalIdField('AppUser'),
	name: {
	  type: GraphQLString,
	  description: 'The name of User',
	},
	surname: {
	  type: GraphQLString,
	  description: 'The surname of User',
	},
  }),
  interfaces: [nodeInterface],
});


var queryType = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    node: nodeField,
    // Add your own root fields here
    appsales: {
      type: appSalesType,
      resolve: () => getAppSales(),
    },
	appuser: {
		type: appUserType,
		resolve: () => {
console.log('aaaa', ModUser.getModUserById);
			ModUser.getModUserById;
		},
	}, 
  }),
});
==== partial schema.js stop -====== 


when the script executed it goes to var queryType ---> appuser 
In the browser grapqhql post (inspect element i see result NULL)

in the CLI 
if I console.log('aaa', ModUser.getModUserById)
it shows 
return new Promise((resolve, reject) => {
		ModUser.findOne().exec((err, res) => {
			if(err){
				reject(err);
			}else{
				resolve(res);
			}
			//err ? reject(err) : resolve(res);
		})
	});

If I use console.log('aaa', ModUser.getModUserById) 
I get the following in CLI
aaaa { 'Symbol(record)_3.aa68p23em81714i':
   { p: [Circular],
     c: [],
     a: undefined,
     s: 0,
     d: false,
     v: undefined,
     h: false,
     n: false } }

What could have been wrong in my script?

**Comment by sayden** [comment]
Hi @spyalert01 

I moved your question to issues in my repository. I'll answer it there to not generate "spam" here.

Any other question regarding the project, please open issue here: https://github.com/sayden/relay-mongoose-example

**Comment by spyalert01** [comment]
@sayden, 
thanks. I can't post an issue there initially.

**Comment by sayden** [comment]
Hi @josephsavona @steveluscher 

I've been abroad and I couldn't fix this properly. I have the example working with mutations already as @josephsavona point me. I have also added some easy navigation using url parameters.

I have to say that mutations lacks a bit more documentation to understand well how it works. It has been more a trial an error process until I managed to make it work.

For example, it confused me for one entire day that `clientMutationId` was always 0 when capturing the request of the mutation until I realized that performing a second mutation gives it an `clientMutationId` of 1, etc. I was thinking that `clientMutationId` must be the id of the object to be mutated.

I have also in the To-do the pull-request to relay-starter-kit. Anyways, I think it is ready if you want to reference it in the React Community Roundup yet.

**Comment by Aourin** [comment]
Simple Mongoose and GraphQL integration.
```

//Cheese Mongoose Model for MongoDB
import mongoose from 'mongoose';

const CheeseSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  type: {
    type: String,
    required: true
  }
});

const Cheese = mongoose.model('Cheese', CheeseSchema);

//Some Root Query
export const Root = new GraphQLObjectType({
  name: 'Query',
  description: 'The <Root> query object',
  fields: () => ({
    cheeses: {
      type: new GraphQLList(GraphQLCheese),
      description: 'A list of <cheese>',
      resolve: (root, params) => {
        return Cheese.find();
      }
    }
  })
});
```

There is obviously a bit more complexity you can build in (also with some separation), but this is just a simple quick snippet.

**Pull request closed without merging**
