### PR TITLE
Edit README.md to discribe requirement of babel-cli

### PR DESCRIPTION
**Pull request by tkshi**
This example requirement two global module.`babel-core`and `babel-cli`.Although,There is not describe in `README.md`.
So I fixed it.

### CODE REVIEW

**Comment by yungsters** [comment]
We actually need more than just these steps. Some of our build steps require some upgrades and/or a `.babelrc` file in order to be compatible with Babel 6 out of the box.

The safest command to use for now is `npm install -g babel@5.8.35`. But an even better improvement is upgrading everything to support Babel 6 without any global installs.

**Comment by edvinerikson** [comment]
Seems like https://github.com/facebook/relay/pull/813 fixed both the upgrade to Babel 6 and the global dependency requirement.

**Comment by edvinerikson** [comment]
However the examples install docs doesn't work out of the box (https://github.com/facebook/relay/issues/906). I could install all dependencies without any errors if I added `--ignore-scripts` to the install command. Maybe we could change this PR to document that instead?

**Comment by josephsavona** [comment]
Per @edvinerikson's comment it looks like this isn't sufficient for running the examples. Let's continue discussion in #906 and move forward with a new PR when a full solution is identified.

**Pull request closed without merging**
