### PR TITLE
Expose Relay.QueryConfig as a public method

### PR DESCRIPTION
**Pull request by washt**
@steveluscher should we go ahead and depreciate `RelayRoute` here too?

### CODE REVIEW

**Comment by wincent** [comment]
Thanks for the PR @washt. Just trying to understand the intent here. Do you have some context that you can link to here for why you want to do this? `RelayQueryConfig` itself doesn't really do anything at all, so I am not sure of the value of exposing it. The rest of Relay really only cares about the interface, `RelayQueryConfigInterface`.

**Comment by wincent** [comment]
...aaaand I found it ([here](https://github.com/facebook/relay/pull/1254#discussion_r69777267)).

**Comment by josephsavona** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing.If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3672274) to review internal test results.

**Pull request closed without merging**
