### PR TITLE
Fix indentation, remove dead return

### PR DESCRIPTION
**Pull request by dmnd**

### CODE REVIEW

**Comment by wincent** [comment]
Thanks!

**Comment by wincent** [comment]
@facebook-github-bot shipit

**Comment by josephsavona** [comment]
The `return undefined` is intentional here; its purpose is clearly stated in the comment at the top of the function.

**Comment by wincent** [comment]
If only I had seen the top of the function... a bit too subtle for me in GitHub's UI:

fix_indentation__remove_dead_return_by_dmnd_ _pull_request__1128_ _facebook_relay

However, despite the almost invisible comment, that statement looks like unreachable code to me.

**Comment by josephsavona** [comment]
I apologize, I didn't read the code carefully enough. Carry on.

**Pull request closed without merging**
