### PR TITLE
Converts Relay website to use Docusaurus. Moved old files into /old.

### PR DESCRIPTION
**Pull request by ericnakagawa**
This PR converts Relay website to use Docusaurus.

Docs front-matter in markdown were scraped to leave only title and id. The sidebars are manually maintained using sidebar.json (this is easier than modifying markdown file next/prev).

Tentative localization support is in place (crowdin.yaml)

Still to be done: design tweaks, algolia keys (we'll provide this shortly).

### CODE REVIEW

**Comment by yuzhi** [comment]
https://relay-oxnnxxivea.now.sh/

**Comment by ericnakagawa** [comment]
Updated live site with Algolia search enabled can now be found here: https://relay-zqicjizexm.now.sh

**Comment by kassens** [comment]
Made some further tweaks, I think we're ready to ship this soon at #2181.

**Comment by kassens** [comment]
Closed by #2181. Thanks for getting this started!

**Pull request closed without merging**
