### PR TITLE
v1.5.0-rc.1

### PR DESCRIPTION
**Pull request by jstejada**
Update version to v1.5.0-rc.1 release candidate

### CODE REVIEW

**Comment by nodkz** [comment]
👍🎉🚀 yeah!

**Comment by graingert** [comment]
Is there any release notes? /cc @nodkz

**Comment by kassens** [comment]
This is how far I got with the release notes so far: mark the commits that seemed interesting to pull out:

```
	640e831b automatically add generated files to source control
	6638eed8 getWriter takes an options object
	2106602c Fix rendering fragments in quickstart
	d77a34c6 Consolidate graphql scripts' usage of `nullthrows`
	effca4a9 $FragmentRef<> utility type
	5843707b Fix non-canonical JS class property usages
	eda7946d Revert D6674250: [relay] add source control operations to CodegenDirectory
	d28119ad Refactor ReactRelayQueryRenderer to improve readability and decrease complexity
X	4baa970d Fix GraphQL parser when input is non-null and passed to calls taking null and non-null args
	1a27a071 fix Flow types in GraphQLMutatorConstants
	083def83 Fix typo in Relay Store docs
	7d326726 add source control operations to CodegenDirectory
	cfc74e23 warning should use a static string
	4cce2a2b Upgrade build deps
	475585b7 Require valid expect
	2732f1b5 Move from `getGoldenMatchers` to jest snapshots
	ce02ec17 @allow-large-files [Flow] Upgrade xplat/js to flow v0.63
	1a8211e5 Update contributing license information
	07a26726 Quickstart guide typo fixes
	8c4e7287 Update Introduction-IntroductionToRelay.md
	c60f8d5f Fix getting started link
	c34a034e Improve refetch docs / address confusion about re-rendering
	a4985c15 Fix Flow typing for RelayEnvironment
	6377b914 Update USERS.md to include Cirrus CI
	37624217 Remove RelayMutationConfig type
	e1326a32 ignore gh-pages branch
	2c96e015 Delete Relay Classic docs
	fbc8a8bb Add Cirrus CI as a user
	99f61fed remove unused customCssFileName config
	3173131e replace last users of GraphQLMutatorConstants
	4cac771e docs(Introduction): Remove duplicate article
	fe0e70f1 docs(Quickstart): Fix spelling of "whether"
	373078fd Codemod Relay/oss/*-test.js
	4d822cdf Include `retry` in QueryRenderer docs
	dc1de353 rename deferred to deferrable
	5a6ded2e use isInputType instead of isScalarType to check idArg in deferrable transform
	1a876adf add mock before codemodding tests
	472edd09 Move declarative mutation flow types to RelayRuntime
	62d6673d Fix typo in Modern-Mutations.md
X	e75a6143 Upgrade graphql-js to 0.12.3
	52265f3a fix missing RelayClassic_DEPRECATED tags
	e5685151 rename setRelayModernMutationConfigs to RelayDeclarativeMutationConfig
	253b1c73 flow for GraphQLMutatorConstants
	6db48cbe Fix typo
	b3261d71 Rename GraphQL Relay spec to GraphQL Server spec
	b3b3f937 Minor cleanup to New in Relay Modern guide
	895e3306 small refactor in setRelayModernMutationConfigs
	0704cf14 reduce indentation in setRelayModernMutationConfigs
	cbc62899 Backed out changeset 688c3d397849
	09dbccbd Final cut of docs version v1.4.1
	a45e8bf7 Rearrange docs for compiler + add @arguments docs
	65e743a9 Upgrade to jest@22.0.3
	4a913da1 move test utils to their own package
	e1be51b7 Export CodegenWatcher in graphql-compiler
	42085b38 Upgrade graphql installation to 0.12.3
	d3d19e0d Converting Mutations
	0698ba59 loading state for deferred fragments
	743cc68b Minor update to Intro page
	e0089841 Update pagination container docs
	4da84be1 Update Refetch Container docs
	bf1b284e Add docs to specify the props received by fragment containers
	52a5398e Update docs for fragment container
	600b217e Minor cleanup in relay store docs
	16eb1db6 Explicitly mock RelayRoute in RelayTestUtils
	4b528a0d Update PrinciplesAndArchitecture-Videos.md
	bf37d8d0 move ARCHITECTURE.md files into docs
	b99edf63 Upgrade Docusaurus to 1.0.3
	0a4027d4 move Variables to RelayRuntimeTypes
	e257cc18 Update docs for Relay Store
	991bf8ac Fix docs versioning (follow up from D6554926)
	f170df52 Add a section in mutation docs on how to use updater and optimisticUpdater
	6ad8b246 Update mutation docs
	3016147f Update QueryRenderer docs
	974ebb65 Initial version of new docs section outline
	d0a4967c Add docs versioning + hide classic docs under "classic" docs version
	3c2069bb Remove unnecessary mocks
	cbc584e5 generate Flow types for query variables
	2ba20d1f cleanup flow types: DataID
	4bf326bb cleanup flow types: Disposable
	b92288c4 run prettier
	383f5743 Rename all classic docs files under the classic- namespace
	ebba2fb2 Collapse GraphQL Relay Specification into a single document
	5255ae2c Add mutation docs to Quick Start guide + some cleanup
	80c19a79 Partially add new quick start guide section
	32ce0cbe Update Introduction section
	f8426aa5 Create new Principles & Architecture section and move "Thinking in" guides there
	47fbbf5f Remove old videos section
	359c2f4c Update to Flow v0.61.0
	fa8fe6b4 remove docs of deprecated relay-babel-plugin
	b3757852 Update docusaurus to 1.0.0-beta.15
	4b1b3d44 Pass over "Thinking in Relay" for RelayModern
	feef3d49 Fix indentation in mutation docs
	0446832c fix requiring graphql-compiler in public build
	4569f3a5 Don't try to write deferred operations
	88041f15 simplify state in ConnectionTransform
	a0e8a6c0 Upgrade to 1.9.1
	e8337f01 simplify invariant calls
	161aa0cb change suffix of GraphQL fixtures to graphql
	f207ffdc fix instagram crash on synchronous fetch
	c8199d53 slightly improve error message from GraphQLRange
	d4ce9a43 Remove transitional utils
	e215cc03 Remove definitionName utility
	1503acc9 Move utils to relay-runtime
	faa6f4d1 @allow-large-files [flow] deploy flow 0.60
	0cbbbac8 Update <OperationType> to inline code
	cbe71d11 fix container flow typing for any props
X	4c7309e6 remove RelayModernTyped
	29dbb55e enforce unique definition names
	b7dc6366 Flow type RelayCompathg
	8c689a7b docs(GettingStarted): fix link on modern network layer
	ec14d61e Add CircleCI config for website deployment
X	c4d1d3b1 Make QueryRenderer render data immediately if data for query is already available in store
	cdc832b1 Add Environment#check to classic environment
	e581d18c Remove $FixMe flow suppression
	19b95914 Fix various tests
F	0d39241c make containers typed
	aca48cd6 Convert some remaining Relay haste modules
	6f30af24 Use explicit mocks instead of enableAutomock()
	e17793e4 Remove GraphQLIRTransforms
	cd79df03 Replace GraphQLCompiler with compileRelayArtifacts
	a1a1dae6 Memoize compiler context transforms
	1e5fffb6 Migrate $FixMe -> $FlowFixMe (take 2)
	67093ddd Remove mutable addDefinitions() from compiler
	e3c6db82 CompilerContext holds both server and client schema.
	f9a15716 remove last traces of Relay2QL
	65a2915e fix flatten transform for non-simple types
	d5f91933 Change $FixMe to $FlowFixMe
	08ddcef1 Dedupe schema between Compiler and CompilerContext
	433d2c4c move RelayCompiledTypes
	b6490223 Improve compiler perf with common transforms.
	b4161d11 Fix lint warnings
	b5c62f7b Transform deferrable fragments into batches
	9bcd0092 Add CODE_OF_CONDUCT.md
	337aed90 Fix flow type for GraphQLResponse
	b83cc4bf Fix Travis CI build (Node 6 support)
	85f8798b Set metadata from relay directive on fragment spreads.
	4143b462 Variable IR include input type.
	4f8f815d Persist all requests within a batch
	1ef72ccf Update RelayModern flow typing strategy
	6a3568ae Change storage key format.
	6caf6224 Remove stableJSONStringify
	4dad1616 Use stableCopy for query cache keys
	c855652d Ensure variables used in getStorageKey are stable.
	d1591169 Stablize literal values
	068e3846 Implement getStorageKey in terms of formatStorageKey
	e61133ed Add getStableStorageKey to RelayRecordProxy
	188df18b Use getStorageKey in ResponseNormalizer for HandleFieldPayload
	2bec3b4f Create getHandleStorageKey()
	1ac7fb69 use getStorageKey in RelayCodeGenerator
	5f0f9b7d Introducing dependencies between operations in Batch Request
	e11bf698 Remove invalid Flow types
X	015330b1 Add hooks to enable and disable Relay GC to RelayFBEnvironment
	a2b5c2eb Rewrite FlattenTransform
	2ac053c1 update QueryRenderer to retain multiple payloads
	734903ed Write to store with operationSelector for current request
	4ae6258b move prettyStringify
X	47632387 Don't warn on missing fields w/ abstract types
	3a8d25f7 Fix toWarn() by passing message as a function
	c9ca62e8 Pull `UnboundedConnectionChecher` validation rule into Relay
	1d86fe14 Speed up RelayMaskTransform
	ad2019c0 Delete unused classic RelayGarbageCollector
	36e2c834 simplify test
	32253189 remove isOptimistic from RelayResponsePayload
	f76f12a5 Change return type of execute from RelayResponsePayload to ExecutePayload
	45d58441 make validation of FindGraphQLTag an option
	5e2b348a Add `subscriber` to `refetch`
	ce1545ea Add "payload action" to network layer for supporting customized disk cache
	29845074 Flow 0.59 xplat/js deploy
	2c96a39d Fix siteConfig.json for local development
	51e8b54b Profiler for Compiler
	a24be3fa Remove AutoAliasTransform
	f41cf0a0 fix prettier issue
+	be62c459 Speed up getIdentifierForSelection
	088b8c4f Dogfood FB products in FB products.
	fcad2fc0 Various small tweaks to the website
	f0eda0cf Fix key warning in website
X	7f2013d6 Fix a bug of using multiple connectionInfo for RANGE_ADD
	722b78a1 Use Docusaurus for the website
	a39a3dbb Using cache config to pass query priority
	47532b9d Suppress errors in Relay.
	6424fbc6 Clean up external callsites of graphql-compiler
	b5baedf0 Remove last deep-nested graphql-compiler deps
	a17b462b Fix end cursor when fetch returned zero edges
	dc420e20 Don't reuse watchman clients
	e1e1dcef optionally wrap validation in conditional
	42b31be4 Update Jest to 21.3.0-beta.8
	e9db559e Optimize CompilerContext
	c6d30136 Print timing information in --verbose mode
X	a628637d check fragment hashes in babel-plugin-relay
	b45baa48 Adds support for batch requests in RelayFBNetwork
	7c0d35f5 export RootContainerProps type
	80d8f64a pass filename to all tests in BabelPluginRelay
	484822ad refactor BabelPluginRelay-test
	020fd6d2 add main entry to relay-compiler/package.json
	1d2262c2 generate hash on modern generated files
	1d023b33 simplify format module
	916483cb @allow-large-files Flow 0.58 upgrade for xplat/js
	bd1df318 Update config to allow some node style requires
	5426401d Use switch in SkipUnreachableNodeTransform
	9ae4d593 Deprecated otherwise removed method.
	76c20eac support fragments with only client fields
	10767462 Compiler transforms use IRTransformer instead of reduce()
	0048a639 use context.getFragment
	c1f20edb Remove classic and tools from RelayPublic
	1cea442c add FB internal keys to package.json
	02c40583 convert RelayGenerateIDFieldTransform to IRTransform
	2e2ab400 Support covariant values in Observable flow types.
	9f66ac4b Fixed comparisons of REQUEST to OPERATION and operationKind.
	d7ba1b06 relayUnstableBatchedUpdates plain .js
	e1782815 Support batch request in createRelayNetworkLogger
	ecc83268 convert RelayGenerateTypeNameTransform to IRTransform
	1ba7ae08 generate type transform no longer sorts
	f1355032 Add batch arguments for ConcreteBatchRequest
	88042547 auto-lint files that were affected by dehastification
	1d72862f Get github gulp-build working
X	a736d7a1 Update all callers of react-relay to use haste-compatible CommonJS require
	ba4759b2 Add tests to de-hastified config
	6b0ec649 Strip providesModule from react-relay
	9e67b63d Fix relayUnstableBatchedUpdates in CommonJS world
N	0a20df1b Add a ConcreteRequest type
N	26d0bf85 Allowed 'OperationDefintion' query kind in fetchRelayModernQuery
	022b7e12 Add BatchRequest generated artifact flow types
	a70e333b add GraphQLCompilerContext.applyTransforms
	ad4d29ae name all transform functions
N	85e5ac15 New ConcreteNode format supporting Batch requests.
N	c058ffc4 (Reapply D5944492) Change return type of `execute` to include operation and variables
	92c2c542 Revert D5944492: [relay] Change return type of `execute` to include operation and variables
	427b11b5 Change return type of `execute` to include operation and variables
	02105df9 Fix up some getters to be flow-safe
	d8381bc1 @allow-large-files Upgrade xplat yarn.lock's for flow-bin@0.57.3
	fc6f6c9a remove timing information from relay compiler output
X	bb02769f Unwrap GraphQLNonNull before writing value
	97f24f8e Dehastify react-relay: squashed diffs into one
	45d3a887 remove leftover reference to PATENTS file
	3aaec291 Remove accidentally added file
	7f490767 Fix unmask transform in RelayCompiler
	aa5f9299 @allow-large-files Deploy Flow v0.57.2
X	03985855 Remove an `invariant` check from `RelayConcreteVariables`
	a34c4df0 Avoid using fbjs modules at all
F	a8e5e0d2 import fragments from other .graphql.js files
	df976f96 Fix haste import in CodegenRunner
	fec11b19 Upgrade babel generator
X	6e4853cf remove graphql.experimental
X	f442fcd4 calling viewer handler multiple times should not accidentally cause viewer to be null
	6f3581e2 updated QueryRenderer flowtype for render prop
	8d9c8e19 remove unused suppressions from xplat/js
F	aa24e999 improve flow generation for GraphQL enums
	74da413c refactor passing of state in Flow generator
F	c5cad09b generate refs in the generated flow types
F	be91ef3e add placeholder value to enums
	353d05af speed up compilation of generated enums file
N	2a0ea7ed Introduce ExecutePayload to network
F	0cf545be generate file for GraphQL enum values
	f2d27ee7 move printing of changes to CodegenDirectory
	ef100ee6 Convert haste style imports in graphql-compiler
D	d88ed376 Update to latest GraphQL.js dependency
	6347efa5 delete graphql-compiler/yarn.lock
	979cb0bc Flow-safety in GraphQLCompilerContext in flow 0.56
X	42c11193 Fix for single item "list" input arguments
	37dbf448 Upgrade Flow to v0.56.0
	62c333f4 factor out optional creation of union/intersection types
	7945175d dedupe JSON in generated files
	d8fe5bac add parens to generated flow code
	7ec99036 bring generated Flow code closer to Relay's codestyle
	17d06cc3 Change all calls to no-console from no-console-disallow
	8f293622 Update type on VisitFn to be more accurate.
	d4823d2d Add suppression comments needed in www for the Flow v0.55.0 upgrade
X	ec3e9eaa dedupeJSONStringify
X	52386e45 Actually remove RecordSourceInspector
	510ff36a v1.4.1
```

**Comment by graingert** [comment]
X	c4d1d3b1 Make QueryRenderer render data immediately if data for query is already available in store

hype

**Comment by taion** [comment]
That's awesome!

... now how do I keep stuff in the store instead of immediately GCing it? 😜

**Comment by robrichard** [comment]
@taion looks like it's now supported via "private" methods in RelayMarkSweepStore: https://github.com/facebook/relay/blob/master/packages/relay-runtime/store/RelayMarkSweepStore.js#L195-L203

I agree it would be great if these were part of the public API.

**Comment by jstejada** [comment]
@taion, @robrichard 
> ... now how do I keep stuff in the store instead of immediately GCing it? 😜

Right, this feature is just experimental/unstable for now, given that GC is a barrier for it to actually work, so I wouldn't depend on it, and probably wouldn't add it to the release notes either.

**Comment by graingert** [comment]
Is there any docs for deferrable fragments?

**Comment by kassens** [comment]
@taion: @robrichard  is right. You can play around with it using that private API for now, but for now we're using it to see how it effects product metrics (memory cost vs. interaction speed). Things are looking pretty good so far and we'll probably find a way to make this official soon.

@graingert: The deferrable fragments use a "batch" network endpoint that supports dependent queries. This is currently not specified officially and the implementation that FB uses has a lot of legacy cruft that should be cleaned up and written with the knowledge gained over the years to make it nicer. Besides we found that in many cases deferring might not be only positive because it causes additional re-render cycles. Still something that's pretty cool and hopefully makes more progress in the future.

**Comment by graingert** [comment]
With STORE_THEN_NETWORK is there a way to tell if it's stale data or not?

**Comment by jstejada** [comment]
@graingert not really -- the way it currently works, `STORE_THEN_NETWORK` will fulfill the query with the latest data it has available in the client-side store (if the data for the _whole_ query is available), and simultaneously send a request to fetch the query from the server. The idea is that this would allow you to momentarily show this stale data, if you're okay with that, if it's already available client-side, as opposed to a loading state. (As mentioned above this won't really work without disabling GC)

Ideally, we could expose some sort of TTL or another expiration mechanism to decide if the data is "fresh" enough to display.

**Comment by graingert** [comment]
> if the data for the whole query is available

Is there any way to start rendering even if only parts of the query are
available in the cache?

**Pull request closed without merging**
