### PR TITLE
Add an "indirection layer" to avoid type conflicts

### PR DESCRIPTION
**Pull request by NevilleS**
...this is a first stab at a fix for #782. It should fix the issue for at least some subset of FIELDS_CHANGE mutations, but might create new issues in other cases, doesn't correct the query building code for RANGE_ADD or RANGE_DELETE, and still needs more work.

But it does create a test case that at least demonstrates one example of the issue!

### CODE REVIEW

**Comment by NevilleS** [comment]
See the discussion in #782 for some context as to why I'd open a PR that definitely isn't ready :+1: 

(also, PR #1000 :100: :100: :100: :100: :100: :100: :100: :100: :100: :100:)

**Comment by josephsavona** [comment]
cc @wincent, @yuzhi re problems with automatic query construction. This is more evidence to suggest for requiring that mutation query construction be more static/manual/explicit.

**Comment by NevilleS** [comment]
Did you guys ever get a chance to think about this? We've got several places in our codebase with `// TODO: https://github.com/facebook/relay/issues/782` and hoping there'd be a better solution than the indirection layers... 😢

**Comment by sibelius** [comment]
👍

**Comment by wincent** [comment]
> Did you guys ever get a chance to think about this? We've got several places in our codebase with `// TODO: https://github.com/facebook/relay/issues/782` and hoping there'd be a better solution than the indirection layers...

I think there are a couple of main alternatives here:

1. Switch to Relay 2 when it comes out ("soon", watch our meeting sync notes to get the latest status on our progress towards being able to push a preview to a branch on GitHub); here all queries, including mutations, are entirely static, and there is no dynamic runtime query generation (no tracked queries, no fat queries, no intersection), so this issue just goes away.
2. Use the existing low-level mutation API, `RelayGraphQLMutation` (shipped, but not documented, as it was really just a step towards what we wanted to build in Relay 2): this also an entirely static mutation API, where you supply your own query and there are no fat/tracked queries or intersection involved. This is still somewhat of a rough API, and because it sits on top of all the "legacy" underpinnings in terms of mutation queues, transactions etc it does have some limitations that make it not as flexible or powerful as what we'll have in Relay 2.

In the meantime, @NevilleS, what do you want to do with this PR? I see two options: either abandon it or update it. What do you think?

**Comment by NevilleS** [comment]
I think the right thing to do is abandon this PR and we'll wait for Relay 2. When we originally hit this issue the low-level mutation API wasn't available, so if this becomes a larger problem for us that workaround will also work - in the meantime, our "manually-inserted-indirection-layer" hack lets us use the declarative mutation API so we'll continue to use that.

Looking forward to fixing some of this stuff with Relay 2, though!

**Pull request closed without merging**
