### PR TITLE
Add an option to generate esmodule imports/exports in babel-plugin-relay & relay-compiler

### PR DESCRIPTION
**Pull request by vincentriemer**
In order to be compatible with bundlers like rollup, which without extra configuration does not support commonjs modules, so this PR adds an `esmodules` option to both `babel-plugin-relay` and `relay-compiler` so that it can generate es modules instead of commonjs. The new config option in both packages will default to `esmodules: false` so this shouldn't (hopefully) be a breaking change.

### CODE REVIEW

**Comment by alloy** [comment]
Rather than adding another configuration option, I wonder if this would be possible to do as a language plugin. For instance, our TypeScript plugin emits ES modules, rather than CommonJS (which is also why the Babel plugin is currently already able to read ES module files).

I would imagine the plugin would basically just re-export the Flow plugin, but amend the generated module. This also alleviates the need for a “hacky” approach to exist in the canonical code-base.

**Comment by vincentriemer** [comment]
That makes sense to me, but I'd still need to keep the esmodule option on the babel plugin (thankfully not as hacky). I'll remove the relay-compiler commit.

**Comment by TrySound** [comment]
@vincentriemer Did you see my PR?
https://github.com/facebook/relay/pull/2781

**Comment by alloy** [comment]
@TrySound I did not, sorry, was out of the loop for a bit.

@jstejada Any thoughts?

**Comment by vincentriemer** [comment]
@TrySound Sorry I didn't! Your PR looks cleaner so I'll close this one, thanks!

**Pull request closed without merging**
