### PR TITLE
Fix tests: add ReactDOMServer to the module map for Jest

### PR DESCRIPTION
**Pull request by denvned**

### CODE REVIEW

**Comment by cpojer** [comment]
@facebook-github-bot shipit

Just for reference, was usage of this module added recently? When I updated jest last week, all the tests were passing :)

**Comment by denvned** [comment]
Yeah, it was added here: https://github.com/facebook/relay/commit/36472364f09ab1213adc2fbe951a508c1f2576b1

**Comment by denvned** [comment]
And last time I updated that PR (https://github.com/facebook/relay/pull/625), all the test were also passing :smile:

**Comment by cpojer** [comment]
@facebook-github-bot shipit

**Comment by cpojer** [comment]
what's up with the bot? Is it dead? @yungsters

**Comment by cpojer** [comment]
There you are buddy! Thought you were taking the Sunday off.

**Pull request closed without merging**
