### PR TITLE
Adds back the missing resolver type import in Typescript files

### PR DESCRIPTION
**Pull request by Markionium**
When trying to improve Typescript types we made the wrong assumption that the resolver type import was always unused in Typescript files. 
We missed the fact that it is used in the scenario where `RelayResolverType` is provided as the return value of a resolver. (See issue #4790)

The TODO's remain as there is still work to do to add Context support to the resolvers.

### CODE REVIEW

**Comment by captbaritone** [comment]
Hey. I'm hitting an internal infra issue importing this PR. I think there's some cases where if a PR needs to get rebased on import it can time out. Sorry to ask this, but do you mind reopening this as a new PR?

**Comment by Markionium** [comment]
@captbaritone do we still need this though? Didn't you do almost exactly the same here?

https://github.com/facebook/relay/commit/4782743b8b0f2bc7a0cc133b92628e92e0ef57ac

**Comment by captbaritone** [comment]
Ah, right. I last track of that. Should we just close this PR?

**Comment by Markionium** [comment]
Yep, closed!

**Pull request closed without merging**
