### PR TITLE
Upgrade to GraphQL 0.6.0

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by steveluscher** [comment]
Do you have a quick fix for these callsites @leebyron, since `getPossibleTypes()` has moved? I don't understand all of the implications at first glance. https://github.com/facebook/relay/search?utf8=%E2%9C%93&q=getPossibleTypes

**Comment by leebyron** [comment]
All `type.getPossibleTypes()` are now `schema.getPossibleTypes(type)` - lookin at the others...

**Comment by steveluscher** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1562845960676028/int_phab) to review.

**Pull request closed without merging**
