### PR TITLE
Added documentation about the disposable.

### PR DESCRIPTION
**Pull request by jasoncarty**

### CODE REVIEW

**Comment by edvinerikson** [comment]
Would it make sense to add a similar example as what refetch have as well?
https://facebook.github.io/relay/docs/en/refetch-container.html

eg
```js
type Disposable = {
  dispose(): void,
};

requestSubscription(
  environment: Environment,
  config: {
    subscription: GraphQLTaggedNode,
    variables: Variables,
    onCompleted?: ?() => void,
    onError?: ?(error: Error) => void,
    onNext?: ?(response: ?Object) => void,
    updater?: ?(store: RecordSourceSelectorProxy, data: SelectorData) => void,
    configs?: Array<RelayMutationConfig>,
  },
) => Disposable;

**Comment by jasoncarty** [comment]
That could be helpful!

**Comment by alloy** [comment]
@jstejada This looks good to me.

**Comment by jstejada** [comment]
thanks!

**Pull request closed without merging**
