### PR TITLE
Revert ES6 classes in Relay website

### PR DESCRIPTION
**Pull request by spicyj**
This reverts commit d5f84d5240bd98791882cc5eed520f32cbab36c9. The website is on an old version of React so we probably don't want this.

### CODE REVIEW

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-4** [comment]
I will not rubber stamp and land your change for you @spicyj!  I can import it for you and you can get your change reviewed by someone though :)

**Comment by cpojer** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1150461298344138/int_phab) to review internal test results.

**Pull request closed without merging**
