### PR TITLE
Add SwissDev JavaScript jobs as user

### PR DESCRIPTION
**Pull request by Vrq**

### CODE REVIEW

**Comment by Vrq** [comment]
@jsierles  @josephsavona would you mind having a look?

**Comment by Vrq** [comment]
@kassens, could you check it out please? :)

**Comment by Vrq** [comment]
@tyao1 would you mind having a look? 🙈

**Comment by Vrq** [comment]
@jstejada could you please have a look? 😃

**Comment by sethwebster** [comment]
Hey @Vrq -- Is SwissDev using Relay? Is there somewhere we can see it in use?

**Comment by Vrq** [comment]
@sethwebster We started using it https://jobapp.swissdevjobs.ch/ and potentially will also use it for new apps.

**Pull request closed without merging**
