### PR TITLE
Fix babel-relay-plugin for babel 6.x

### PR DESCRIPTION
**Pull request by amenuor**
Fixes issues with transpiling graphql queries code with babel 6.x as described in #533

### CODE REVIEW

**Comment by leebenson** [comment]
@amenuor @joshuaevenson - Any news on this? It seems to be failing at:

```
Cannot find module 'babel-types/lib'
```

**Comment by amenuor** [comment]
@leebenson of course the build fails. To have that work correctly the whole project need to be updated to use babel 6. 
I have looked briefly into it and it is quite a major change. 
I can work on it if needed since I started this...

**Comment by leebenson** [comment]
@amenuor I included you on this since you kindly submitted a PR, but this is more a prompt for FB re: next steps for fix + merge. Babel 6.x seems to be gaining traction, and I imagine this is quickly going to become a roadblock to adoption.

**Comment by amenuor** [comment]
Ah ok :) Let me know if I can help.

**Comment by jwaldrip** [comment]
This is definitely becoming a roadblock. :+1: to getting this merged in.

**Comment by josephsavona** [comment]
@amenuor this PR only contains changes to the files in `lib/`, which are generated. Can you commit the changes to the original `src/` files?

**Comment by amenuor** [comment]
@josephsavona as I stated also in the issue #533 this code is mostly for guidance.
I just focused on how to make it work for the projects I am working on which depend on this plugin.
For simplicity I just modified the output of the generated files. However, from that it should be quite straightforward to modify the source files.

I will check later today if you got this to work, if not I will work on the source files.
Let's get it done :)

**Comment by amenuor** [comment]
@josephsavona I have checked-in the major changes to have this plugin working on babel6.

I have had some issues with es6 Spread operator. Somehow it doesn't work on babel6 (it gives Syntax errors) or I couldn't make it work. Based on http://babeljs.io/repl/ (which still run babel 5.x) I have defined an _extends function and use that instead. Not elegant but it seems to work.

I receive several errors when trying to run the tests and check that everything is actually fine.
Flow doesn't like several hundreds statements in /node_modules/*
Jest complains about some syntax errors related to destructuring assignments as far as I can see...

However, the plugin builds fine... we just need to verify that it actually works :)
I do not have so much experience with Flow and Jest, so if you have maybe you can figure this out faster than I can?

**Comment by leebenson** [comment]
@amenuor for rest/spread, make sure you're including `babel-plugin-syntax-object-rest-spread` in package.json and in your plugins config, as well as `babel-plugin-transform-object-rest-spread` to actually do the _extend transform.

**Comment by amenuor** [comment]
@leebenson well spotted! :) Now it works correctly.
@josephsavona I have checked in the changes, and all tests pass on the plugin side. The build is still failing because of two main issues:

1) the main relay package is not supporting babel6 yet. I only worked on the babel-relay-plugin. I could help also on the main package if needed.
2) Flow gives 7000+ errors. I haven't looked much into it yet, but it seems to be related to the new packages in node_modules (as for instance babel-core).

**Comment by josephsavona** [comment]
If you're on master, babel-relay-plugin should work out of the box with babel 6 as of ba004a4. We'll upgrade the examples, tests, etc to use babel 6 at a later date.

**Comment by josephsavona** [comment]
@amenuor thanks for your help with this!

**Comment by amenuor** [comment]
@josephsavona glad I could help :)

**Pull request closed without merging**
