### PR TITLE
Split Jest and Flow into two build steps

### PR DESCRIPTION
**Pull request by steveluscher**

### CODE REVIEW

**Comment by mroch** [comment]
`npm run typecheck`

**Comment by steveluscher** [comment]
You win some, you lose some.

**Comment by steveluscher** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-7** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/921131174659849/int_phab) to review.

**Pull request closed without merging**
