### PR TITLE
Bump version of Relay and Babel Relay plugin to 0.6.0

### PR DESCRIPTION
**Pull request by steveluscher**
@facebook-github-bot import

### CODE REVIEW

**Comment by taion** [comment]
Does the reversion mean that we should hold off on upgrading to 0.6.0 for now?

**Comment by steveluscher** [comment]
Nope! It was auto-reverted because of some Facebook-internal cache nonsense. I reapplied the commit this morning!

**Comment by BerndWessels** [comment]
Updated [babel-relay-plugin-loader](https://github.com/BerndWessels/babel-relay-plugin-loader/commit/f68feb16b78dbbb83f1c8e8661b9c71d6949385c) to 0.6.0 too.
Cheers
Bernd

**Comment by steveluscher** [comment]
Love it! :heart:

**Pull request closed without merging**
