### PR TITLE
Licence bug fixed

### PR DESCRIPTION
**Pull request by akashnimare**
1. Fixed the licence of examples. Now it is same as define [here](https://github.com/facebook/relay/tree/master/examples/todo#license).
2. Fixed some lint errors and warnings.

Ps - All npm test are passed and lint shows no major errors. Please see the diff.

Npm Test

Lint test

### CODE REVIEW

**Comment by josephsavona** [comment]
@facebook-github-bot import

**Comment by akashnimare** [comment]
@josephsavona Is it ok?

**Comment by wincent** [comment]
@akashnimare: This got held up because our internal linter blocked it. I've now fixed that, so we can proceed to land this.

**Comment by akashnimare** [comment]
Awesome.

**Comment by akashnimare** [comment]
Why it is not merged?

**Comment by wincent** [comment]
It is merged (see 1e1131371f756f46bcbcf739f1b98af1002e6c8a).

**Pull request closed without merging**
