### PR TITLE
Fix some syntax errors introduced by e2ba4a6ca07

### PR DESCRIPTION
**Pull request by chentsulin**
Obviously, there are some syntax errors introduced when code transforming. Try to fix it in this commit, or should we revert it directly?

https://github.com/facebook/relay/commit/e2ba4a6ca07f74cb90984302fb191e17d1e309bd

### CODE REVIEW

**Comment by JenniferWang** [comment]
@spicyj Ben could you please take a look?

**Comment by spicyj** [comment]
There's something broken with the github import (fb-internal link: https://fburl.com/398137359). I'll send a diff internally to fix this because I don't think importing this PR will actually fix it, unfortunately.

**Comment by JenniferWang** [comment]
Will be fixed internally.

**Comment by spicyj** [comment]
Fixed in fab36d9babe36d07e1619d59e2c451515e378c0f.

**Pull request closed without merging**
