### PR TITLE
Remove the `clientMutationId` requirement by creating a new root id for each executed mutation

### LINKED ISSUE #825: Idea: Remove the mutation GraphQL specification requirements?
One of the things I found annoying while trying to implement mutations is how much opinion Relay inflicts on my GraphQL schema—having to create `Input` and `Payload` definitions for each operation is really verbose, very Relay-specific, and not necessarily that “clean” of an API.

For example, ignoring Relay, it might be nice for a mutation in the GraphQL schema to look like:

```
type Mutation {
  createTeam(userId: ID!, team: JSON!): Team
}
```

That would be a fairly simple `createTeam` mutation, that is easy to understand. You pass the `userId` of the user you’re creating the team for, and a `team` JSON object containing team attributes (name, billing email, etc.). It maps fairly simply to a `POST /users/:userId/teams` call of traditional REST APIs (not that that’s a requirement, but REST does have a lot of good patterns).

Unfortunately, implementing that same mutation for Relay requires the GraphQL schema to be very Relay-specifc instead:

```
type Mutation {
  createTeam(input: CreateTeamInput!): CreateTeamPayload
}

input CreateTeamInput {
  userId: ID!
  team: JSON!
  clientMutationId: String!
}

type CreateTeamPayload {
  team: Team
  clientMutationId: String!
}
```

A lot more verbose, but also less easily used by other, non-Relay, GraphQL implementations now. Or at least without them having to adopt Relay’s naming opinions.

It seems like one reason the `Input` is used is so that creating the `$input` variable is as easy as possible for the client code. But it doesn’t seem like this should come at the expense of changing the schema itself. It seems like it would still be easy to implement arbitrary variable names, and have them be stringified properly by the query configuration logic in Relay. Such that passing something like:

``` js
{
  userId: 'user_1',
  team: {
    name: 'Team',
    email: 'team@example.com'
  }
}
```

Could be stringified into a mutation of:

```
mutation CreateTeam($userId: String, $team: JSON) {
  createTeam(userId: $userId, team: $team) ...
}
```

Another reason for the `Input` and `Payload` is to attach a `clientMutationId`, which the documentation suggests is  `used to reconcile requests and responses`. But this seems like something that is NetworkLayer specific, and could be better implemented as a separate parameter to any HTTP calls made to the server, and even something that might need to be use-case specific. 

For example, I already support a `?requestId` parameter on my server for that exact purpose, and others might have differently named solutions. If all that’s needed is a unique identifier for requests, couldn’t it be implemented decoupled from the GraphQL part of the request? Potentially even implemented as an HTTP header instead of as part of the parameters of a request. Seems like something that’s going to be very server-specific, and so should be an option for the NetworkLayer, but have nothing to do with the GraphQL schema itself?

### LINKED ISSUE #1734: How to avoid Dup Records when executing Create Mutation Commits that Insert New Edges into Connections
Having trouble implementing a simple Document Component that adds a document and updates a connection relation with Application.documents edges.  The Create works fine, but the Updater keeps adding the LinkedRecord reference to the same Edge every time I run InsertEdgeAfter on the Application.documents Connection.  This causes duplicate records since it keeps updating the old Edge records by reference.  I'm hoping I don't have to destroy the Component to create a separate reference for the Create Edge LinkedRecord.  How do we add multiple edges to Connections if we always receive the same referenced Edge?

Here is the mutation to create a document, it returns an associated Application.id as well as the expected edge.

```
const mutation = graphql
  mutation CreateDocumentMutation($input: CreateDocumentInput!) {
    createDocument(input: $input) {
      document {
        id
        data
      }
      edge {
        __typename
        cursor
        node {
          id
          application{
            id
          }
          data
        }
      }
      application {
        id        
      }
    }
  }
```

Here is my updater method that gets the payload, finds the Edge, then uses the application proxy to get the Connection to insert the Edge into.  The problem is the Edge is a linked record and every time I run a commit on this create it keeps updating the Edge reference and incrementing pointers to the latest Edge value.

```
updater: (store) => {
        const payload = store.getRootField('createDocument')
        const newEdge = payload.getLinkedRecord('edge')
        const proxy = store.get(application.id)
        const conn = ConnectionHandler.getConnection(proxy, 'application_documents')        
        ConnectionHandler.insertEdgeAfter(conn, newEdge)
      }
```

My connection is simply just a list of the documents for this application.  After I insert each document, the list starts creating duplicates simply because the references all point to the last Edge created.  The GraphQL data storage is fine, but my local update is failing due to this issue.

Application.documents = [
11111,  <- created in an earlier session
2222,  <- created in an earlier session
12345,  <- created in the current session
12345,  <- created in the current session
12345,  <- created in the current session, keeps repeating as I run the commit trigger
]

### LINKED ISSUE #2333: Status Code:204 No Content Remote
I don't know why my server API returns 204 for now, but if I add two items with the same text, Relay will generate the same key.

screen shot 2018-02-21 at 04 46 24

### PR DESCRIPTION
**Pull request by robrichard**
Fixes #1734
Fixes #2333 
Fixes #825

Related to https://github.com/relayjs/relay-examples/issues/30
When a mutation is executed, it's payload is added to the store using a key of the serialized arguments. In the Todo Modern example this looks like this:

```js
{
  'client:root:addTodo(input:{"text":"a"})': { ... } // added by mutation response
  'client:VXNlcjptZQ==:__TodoList_todos_connection': {
    edges: [
      __refs: [
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:0',
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:1',
        'client:root:addTodo(input:{"text":"a"}):todoEdge', // added by mutation imperative updater function
      ]
    ]
  }
}
```

If you execute a second `addTodo` mutation with the same arguments, the `client:root:addTodo(input:{"text":"a"})` field in the store will get overwritten with the second mutation and the store will look like this:

```js
{
  'client:root:addTodo(input:{"text":"a"})': { ... }
  'client:VXNlcjptZQ==:__TodoList_todos_connection': {
    edges: [
      __refs: [
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:0',
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:1',
        'client:root:addTodo(input:{"text":"a"}):todoEdge',
        'client:root:addTodo(input:{"text":"a"}):todoEdge',
      ]
    ]
  }
}
```

When React renders the data, you will have the latter `todo` in the connection array twice and will likely get an error along the lines of `Encountered two children with the same key, <id>. Child keys must be unique; when two children share a key, only the first child will be used`.

This was [fixed in relay-examples](https://github.com/relayjs/relay-examples/commit/ed955945ca5158ac34ed8ce703ae0cc7cb3e38e7#diff-4b42725e6eb503f56da8e3f637e9a4e3) by adding a `clientMutationId` to the mutation arguments. I don't think this is ideal since
1. it requires the developer to manually add this to each mutation
2. it places an additional constraint on the GraphQL schema to support this field.

The approach I took to fix this, was to use a new root `dataID` (instead of the static `client:root`) for results on each mutation. This will namespace results from each mutation so they can never overwrite one another. 

With these changes, the relay store now looks like this after completing the same series of mutations:

```js
{
  'client:mutationRoot0:addTodo(input:{"text":"a"})': { ... },
  'client:mutationRoot1:addTodo(input:{"text":"a"})': { ... },
  'client:VXNlcjptZQ==:__TodoList_todos_connection': {
    edges: [
      __refs: [
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:0',
        'client:VXNlcjptZQ==:__TodoList_todos_connection:edges:1',
        'client:mutationRoot0:addTodo(input:{"text":"a"}):todoEdge',
        'client:mutationRoot1:addTodo(input:{"text":"a"}):todoEdge'
      ]
    ]
  }
}
```

I tested this and it works to solve this issue, but I'm unsure if there could be any unintended consequences by this change.

### CODE REVIEW

**Comment by alloy** [comment]
This PR addresses the issue described in https://github.com/facebook/relay/issues/2333. And while this does not remove the ID, it _is_ related to https://github.com/facebook/relay/issues/2077.

**Comment by alloy** [comment]
@steida Mind testing this PR for your situation? (And is your situation a production app?)

**Comment by steida** [comment]
@alloy My situation is https://github.com/este/este. Not a production 😔

**Comment by steida** [comment]
@kassens What do you think? Should I test it? Is there any chance it will be merged in, say, next six months?

**Comment by alloy** [comment]
@steida We should help the Relay team by testing them preemptively do that when they have time they will know it was already tested by at least somebody.

**Comment by taion** [comment]
Is there a constructive reason for the old behavior, incidentally? It does seem odd to essentially assume idempotency for all mutations.

**Comment by taion** [comment]
BTW, the same problem arises for subscriptions. In this case the fix needs to be applied in this manner, as there's no place to inject a payload sequence ID (as far as I'm aware).

That said, @AndrewIngram's workaround is pretty satisfactory in practice.

**Comment by sibelius** [comment]
@jstejada @kassens can we try to import this again ?

we could also merge this one https://github.com/facebook/relay/pull/2401 when this has landed

**Comment by jstejada** [comment]
thanks for the ping @sibelius! apologies again for the delay in getting to this. We still need to discuss internally a little bit what the best approach would be here. From a short discussion, it seems like we could address separately the problem of ensuring that we don't overwrite mutation payloads vs removing the requirement for a clientMutationID. cc @josephsavona  @kassens

**Comment by steida** [comment]
This open source community PRs neglecting is why people can not trust Facebook open source stuff (DraftJS, Flow) anymore. If nothing change, Relay will die like Flow.

**Comment by taion** [comment]
I just ran into something like this. We've switched our mutations to return unions between the payload type and various typed errors as their root types. When running a mutation with the same inputs leads to a different concrete return type (e.g. an error instead of a payload), we get an invalid record update due to the type mismatch, because the root field gets reused.

**Comment by tlvenn** [comment]
@jstejada do you have any update on this particular issue ? Thanks in advance.

**Comment by jstejada** [comment]
i think @tyao1 already fixed this

**Comment by robrichard** [comment]
@jstejada @tyao1 I'm pretty sure this is still an issue. I just tested in relay-examples todo with relay v7 and was able to reproduce

**Comment by kassens** [comment]
This has been a *long* time coming, thanks @robrichard  for the initial PR and @tyao1 for picking this back up!

**Comment by earksiinni** [comment]
Can someone please comment with respect to the relevance of this PR to the following, taken from the "GraphQL Server Specification" section of the documentation?

> Relay uses a common pattern for mutations, where there are root fields on the mutation type with a single argument, input, and where the input and output both contain a client mutation identifier used to reconcile requests and responses.

Is it correct to say that this documentation is incorrect because client mutation identifiers no longer exist? Or do they exist but they're an internal API (e.g., auto-generated)? Or something else...?

**Comment by sibelius** [comment]
It is still a common pattern, but not a requirement anymore

**Comment by pvgoddijn** [comment]
any guidance on how to implement the mutation identifier when writing a compatible server?

**Comment by taion** [comment]
If you're using JS, graphql-relay provides primitives for this. Otherwise, many other frameworks have their own equivalents. It just depends on which server you're using.

**Comment by sibelius** [comment]
clientMutationId is like an idempotence key (https://stripe.com/docs/api/idempotent_requests)

so your server can validate that user hasn't sent the same mutation twice

**Comment by taion** [comment]
not exactly – it was originally meant for _clients_ to be able to correlate mutation payloads with mutations, without assuming request/response semantics on the network transport

**Pull request closed without merging**
