### PR TITLE
Examples todo update

### PR DESCRIPTION
**Pull request by rosskevin**
- update dependencies
- update usage of react-router-relay
- fix all warnings

Sample is up and running locally with updated dependencies and without any errors.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by rosskevin** [comment]
cla signed.

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by kassens** [comment]
Thanks!

**Comment by kassens** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-4** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1258791597481469/int_phab) to review.

**Pull request closed without merging**
