### PR TITLE
chore(react-relay): Adds scheduler as a dep

### PR DESCRIPTION
**Pull request by maraisr**
fixes: #3076

### CODE REVIEW

**Comment by kassens** [comment]
Thanks @maraisr!

**Comment by kassens** [comment]
We'll include this in the next experimental release, but for now it's harder to merge as we use some experimental branch release of Scheduler internally and we like to avoid using different versions in github and externally.

That said, the next experimental branch releases should be fixed.

**Comment by maraisr** [comment]
I think we should keep this one open Stale bot,

cc @en_js @kassens

**Comment by maraisr** [comment]
fixed in https://github.com/facebook/relay/commit/bf361b32ec0f7d0cee90ff448c9ad4e038e82fdb

**Pull request closed without merging**
