### PR TITLE
Add chinese translation of QuickStart-Tutorial.md

### PR DESCRIPTION
**Pull request by Yaxian**

### CODE REVIEW

**Comment by wincent** [comment]
Thanks @Yaxian.

I'm totally unqualified to review this. Help, @yuzhi!

**Comment by yuzhi** [comment]
I have the vocabulary of about a third grader in China, but the parts that I read looked reasonable. I think the main problem is that we don't have support for multiple languages right now.

**Comment by Yaxian** [comment]
Ok, I got it. @yuzhi you can close it. Thanks.

**Comment by kassens** [comment]
I checked with other people at Facebook how they do it and what I heard from React made sense to me.

While we currently don't have the website stack setup to handle multiple locales, it seems like the React community has found use of the translations anyway.

I think this can be a good start to make entry easier for people worldwide. 👍 

@facebook-github-bot import

**Comment by facebook-github-bot-1** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1762003654030649/int_phab) to review.

**Comment by pengliaoye** [comment]
继续翻译撒

**Comment by Yaxian** [comment]
Sorry, I'm very busy recently. I will go on this weekend. :)
pengliaoye <notifications@github.com>于2016年5月24日 周二上午11:13写道：

**Pull request closed without merging**
