### PR TITLE
Stop requiring Promise, adjust requires tooling appropriately

### PR DESCRIPTION
**Pull request by zpao**
`fbjs-scripts` 0.5 hasn't been shipped yet but tested locally with `npm link`

cc @DmitrySoshnikov

### CODE REVIEW

**Comment by josephsavona** [comment]
@zpao do you mind importing this? lgtm

**Comment by zpao** [comment]
Will do in the AM. Would like to make sure https://github.com/facebook/fbjs/pull/80 is right before shipping 0.5

**Comment by zpao** [comment]
@facebook-github-bot import

**Comment by zpao** [comment]
I got into a state where tests weren't passing but all cleared up now. I split out the changes to the actual `require` statements since @DmitrySoshnikov is doing that separately - this will go in after.

@facebook-github-bot import

**Pull request closed without merging**
