### PR TITLE
[bug report] refetchables don't include required metadata

### PR DESCRIPTION
**Pull request by tbezman**
I created a failing test which shows the issue.

I think the root cause is the following:

- The generated refetchable query doesn't include the required directives used by the source fragment.

### CODE REVIEW

**Comment by captbaritone** [comment]
Sorry, I'm not sure I follow. Could you add a comment on the diff showing what you were expecting to see, or maybe an example of what incorrect behavior this leads to in the runtime?

**Comment by captbaritone** [comment]
Would it be possible to reconstruct this failing tests with something that does not use `@connection`. The compiler error I see is actually related to an issue with connections not refetchable.

**Comment by tbezman** [comment]
@captbaritone I'm also a bit confused. When I remove the `@required` directive from the query, the test at least generates artifacts. What is leading you towards the connection bit?

**Comment by captbaritone** [comment]
The `@connection` transform adds some fields to the selection. These fields can conflict with `@required`, since the added version of the fields are not `@requried` and you are not allowed to have the same field both `@requried` and not required in the same selection.

I think the error you are seeing might be caused by that issue.

**Comment by tbezman** [comment]
@captbaritone I see. So is the accepted workaround to just put your selections in another fragment? Do y'all advocate for this internally?

**Comment by captbaritone** [comment]
Usually I just advocate for doing a manual null check inside your component/hook in these cases.

**Comment by tbezman** [comment]
okay, thanks for the guidance!

**Pull request closed without merging**
