### PR TITLE
added metadata option in commitMutation & requestSubscription

### PR DESCRIPTION
**Pull request by morrys**
this PR allows you to set the CacheConfig metadata parameter directly from commitMutation.

issue: https://github.com/facebook/relay/issues/2804

### CODE REVIEW

**Comment by mrtnzlml** [comment]
Hola @morrys, this would be very helpful for me as well! :) Do you think it makes sense to add it to `requestSubscription` as well? 🤔

**Comment by morrys** [comment]
hi @mrtnzlml,
being a simple change that does not involve any breaking change it makes sense to adapt the requestSubscription too :)

During the week I check and update the PR.

**Comment by morrys** [comment]
hi @mrtnzlml,
I updated the PR :)

**Comment by morrys** [comment]
@jstejada @josephsavona any news about this PR?

**Comment by morrys** [comment]
Friendly ping @jstejada @josephsavona

**Comment by jstejada** [comment]
@morrys if this metadata is intended to be passed directly to the cache config, do you think it'd make sense to rename it to `networkMetadata` or similar?

**Comment by morrys** [comment]
@jstejada with this PR it is used for this purpose but in my opinion with a more generic name it leaves open the possibility of using it for other purposes.

**Pull request closed without merging**
