### PR TITLE
Add warning if still using buildCommand in RelayFileWriter config

### PR DESCRIPTION
**Pull request by AGS-**
@kassens Adding this since it got changed from 1.0.0 to 1.1.0

### CODE REVIEW

**Comment by AGS-** [comment]
I see that the test isn't passing because flow obviously doesn't like that I'm checking for a key that isn't defined in the type. Since buildCommand is deprecated it doesn't really make sense to add it as an optional in the type right?

**Comment by AGS-** [comment]
I don't know what your thoughts are on maybe adding buildCommand back in as optional, warning the user that it's deprecated and replaced by formatModule, and maybe provide a sensible default FormatModule if they haven't provided it. This way it won't break if people upgrade.

**Comment by kassens** [comment]
Maybe create a new `function validateConfig(config: Object): void { /* ... */ }` where you just type as Object and can now check any legacy fields.

**Comment by AGS-** [comment]
Alright, sounds good. I'll update the PR in a bit

**Comment by AGS-** [comment]
@kassens updated the PR

**Pull request closed without merging**
