### PR TITLE
Removed extra "and" in fetch-polocies.md

### PR DESCRIPTION
**Pull request by marcesengel**
Seems to be a typo.

### CODE REVIEW

**Review by alunyov — CHANGES_REQUESTED** [review]
Thank you! Can you also change the source here: https://github.com/facebook/relay/blob/main/website/docs/guided-tour/reusing-cached-data/fetch-policies.md

**Comment by marcesengel** [comment]
@alunyov done :)

**Review by alunyov — APPROVED** [review]

**Comment by alunyov** [comment]
Oh @marcesengel there a few merge-conflicts. Can you look at these?

**Comment by marcesengel** [comment]
@alunyov the conflicts are actually because someone else already merged their fix in the meantime haha

**Pull request closed without merging**
