### PR TITLE
2984 optimizing requestid

### PR DESCRIPTION
**Pull request by morrys**
https://github.com/facebook/relay/issues/2984

Modified the compilation of the artifacts in order to generate a unique identifier (md5 text) for the 'Request' nodes.

modified writeRelayGeneratedFile:

eliminate the switch, the node is always of type Request because inside 'if (generatedNode.kind === RelayConcreteNode.REQUEST) {'

https://github.com/facebook/relay/blob/master/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L98

### CODE REVIEW

**Comment by sibelius** [comment]
this will make persisting the store to cause less memory

more info here https://github.com/morrys/react-relay-offline/issues/34#issuecomment-588248965

**Comment by morrys** [comment]
@jstejada @kassens any news about this PR?
before resolving conflicts I would like to know if you are interested in its integration.
Thanks

**Comment by morrys** [comment]
Friendly ping @kassens @jstejada

**Comment by jstejada** [comment]
@morrys this PR is already imported and we're looking at how to roll it out internally

**Pull request closed without merging**
