### PR TITLE
Update license year range to 2016

### PR DESCRIPTION
**Pull request by pra85**

### CODE REVIEW

**Comment by steveluscher** [comment]
It's that time again, huh? Thanks for doing this!

Care to update this PR to include all references to ‘…-2015’ in Relay code, examples, and scripts?

**Comment by pra85** [comment]
@steveluscher I have updated the pull request to change all instances to 2016

**Comment by josephsavona** [comment]
@pra85 Thanks so much for taking the initiative to do this! @wincent noticed that our other projects are using `-present` to avoid the necessity for yearly updates. What do you think about moving forward with that change (#757) instead?

**Comment by wincent** [comment]
Also happy to close that one if you prefer to re-roll this one @pra85 (either way, they're both in need of a rebase).

**Comment by pra85** [comment]
@wincent I have rebased and updated this pull request to make it `-present` everywhere.

**Comment by steveluscher** [comment]
Nailed it. @facebook-github-bot import

**Comment by vko-online** [comment]
Also, it's __@ Facebook 2015__ in relay website footer

**Comment by kassens** [comment]
@vko-online Thanks, I just sent #959 to update the remaining years.

**Pull request closed without merging**
