### PR TITLE
add Local State Management blog posts from @babangsund, see #1656

### PR DESCRIPTION
**Pull request by jgcmarins**

### CODE REVIEW

**Comment by josephsavona** [comment]
Linking to these is great, but we'd love to have actual docs for using local state. Any interest in writing up some docs?

**Comment by jgcmarins** [comment]
Sure.
Any idea which topics are important to cover?

**Comment by babangsund** [comment]
I'd also volunteer. 🙂

**Comment by jgcmarins** [comment]
@babangsund, completely agree \o/

**Comment by babangsund** [comment]
Sorry for the delay. I wasn't sure who we agreed was doing it, so I postponed it. 😅 
Regardless - https://github.com/facebook/relay/pull/2821

**Comment by jgcmarins** [comment]
https://github.com/facebook/relay/pull/2821

**Pull request closed without merging**
